import type { Subject } from "./types";

export const lit: Subject = {
  id: "lit",
  name: "AP English Literature & Composition",
  short: "Lit",
  tagline: "Close reading, poetry & prose analysis, three essay types",
  color: "#d97706",
  soft: "#fef3c7",
  exam: {
    format: "3 hrs · 55 MCQ (45%) + 3 essays (55%)",
    mcq: "55 multiple-choice, 60 min — 5 passages (poetry + prose) testing close reading",
    frq: "3 essays, 2 hrs: poetry analysis, prose fiction analysis, literary argument (open question)",
  },
  tips: [
    "MCQ: answer in the passage's logic, not your own — eliminate choices with extreme words (always, never) first.",
    "Every body paragraph: Claim → embedded Evidence → Analysis of HOW the device creates meaning. Never drop a quote without unpacking it.",
    "Learn 15–20 versatile terms cold (syntax, diction, juxtaposition, enjambment, unreliable narrator) and practice spotting them fast.",
    "Q3 (literary argument): pre-plan 4 works across genres/eras with themes, key scenes, and devices — never walk in without them.",
    "Budget essays at 40 min each: 5 plan, 30 write, 5 proofread. A complete, slightly short essay beats a brilliant fragment.",
  ],
  units: [
    {
      id: "close-reading",
      title: "Close Reading & Annotation",
      weight: "Foundation",
      concepts: [
        "SOAPSTone: Speaker, Occasion, Audience, Purpose, Subject, Tone",
        "Annotation system: diction, imagery, syntax shifts, punctuation, repetition",
        "Literal vs. figurative meaning; connotation vs. denotation",
        "Identifying tone and tone shifts (the 'turn' or volta)",
        "Paraphrasing dense lines before interpreting them",
      ],
      formulas: [
        "DIDLS: Diction, Imagery, Details, Language, Syntax (tone toolkit)",
        "TWIST: Tone, Word choice, Imagery, Style, Theme",
        "T = tone shift often at stanza breaks, 'but/yet/however'",
        "Paraphrase → observe → connect → interpret (reading ladder)",
        "Complexity = acknowledging ambiguity, not picking one side",
      ],
      practice: [
        {
          id: "li-cr-1", kind: "MC",
          prompt: "A narrator describes a house as 'a sullen monument to unpaid debts.' The dominant effect of 'sullen' is to:",
          choices: ["A) give an objective architectural detail", "B) personify the house with resentful mood", "C) establish a comic tone", "D) foreshadow a wedding"],
          answer: "B) personify the house with resentful mood",
          hint: "Ask what 'sullen' literally describes (a person) vs. what it modifies (a house).",
          solution: "Transferring a human情绪 adjective to an object is personification; it colors setting with mood — resentment/decay.",
        },
        {
          id: "li-cr-2", kind: "MC",
          prompt: "Which annotation habit most improves MCQ accuracy?",
          choices: ["A) underlining every adjective", "B) bracketing structural shifts and summarizing each chunk", "C) counting syllables", "D) memorizing the author's biography first"],
          answer: "B) bracketing structural shifts and summarizing each chunk",
          hint: "AP questions cluster around structure, function, and shifts.",
          solution: "Chunk-summaries map the passage's argument, making function/shift questions fast and accurate.",
        },
        {
          id: "li-cr-3", kind: "MC",
          prompt: "'The wind bit, and the town bit back.' The line's effect relies on:",
          choices: ["A) simile", "B) antithesis and parallel syntax", "C) mixed metaphor", "D) dramatic irony"],
          answer: "B) antithesis and parallel syntax",
          hint: "Two balanced clauses set in opposition.",
          solution: "Parallel structure ('X bit, Y bit back') frames an opposition — hostile nature vs. defiant town.",
        },
        {
          id: "li-cr-4", kind: "MC",
          prompt: "A passage shifts from long periodic sentences to fragments. The most likely purpose is to:",
          choices: ["A) show off vocabulary", "B) quicken pace / signal emotional rupture", "C) confuse the reader", "D) meet a word count"],
          answer: "B) quicken pace / signal emotional rupture",
          hint: "Syntax mirrors psychology: controlled → broken.",
          solution: "Fragmentation after control conventionally signals urgency, panic, or a break in composure.",
        },
        {
          id: "li-cr-5", kind: "FRQ",
          prompt: "Take any 8-line passage you're reading now. Write a 150-word close-reading paragraph: one claim about tone, two embedded quotes, and analysis of one diction choice + one syntax choice.",
          answer: "Self-assessed: claim + 2 quotes + diction + syntax analyzed",
          hint: "Formula: 'The tone is X, established when... The word ___ connotes... while the ___ syntax...'.",
          solution: "Strong response names a precise tone (not just 'sad' — e.g., 'resigned bitterness'), embeds short quotes grammatically, and explains HOW each choice builds the tone rather than restating what it says.",
        },
        {
          id: "li-cr-6", kind: "FRQ",
          prompt: "Paraphrase this line literally, then interpret it: 'I am the wound and the knife.' (2–3 sentences each.)",
          answer: "Literal: I am both injured and injurer; interpretive: complicity in one's own suffering",
          hint: "Literal = plain-English restatement; interpretation = why the paradox matters.",
          solution: "Literal: the speaker is simultaneously the victim and the cause of harm. Interpretation: the paradox collapses victim/victimizer roles, suggesting guilt or self-sabotage — pain the speaker both suffers and inflicts.",
        },
      ],
    },
    {
      id: "poetry",
      title: "Poetry Analysis",
      weight: "MCQ + Essay Q1",
      concepts: [
        "Speaker vs. poet; dramatic situation and audience",
        "Form: sonnet, ode, elegy, villanelle, free verse; meter and rhyme scheme function",
        "Sound devices: alliteration, assonance, cacophony/euphony, enjambment vs. end-stop",
        "Figurative language: metaphor, conceit, apostrophe, synecdoche, metonymy",
        "Structural analysis: stanza breaks, volta, repetition, refrain as argument",
      ],
      formulas: [
        "Shakespearean sonnet: ABAB CDCD EFEF GG; turn at line 9 or couplet",
        "Enjambment = urgency/overflow; end-stop = control/finality",
        "Apostrophe: direct address to absent/dead/abstract ('O Death')",
        "Volta hunting: look for 'but / yet / so / then'",
        "Sound → sense: harsh sounds for conflict, smooth for harmony",
      ],
      practice: [
        {
          id: "li-po-1", kind: "MC",
          prompt: "A sonnet's final couplet reverses everything the first twelve lines argued. This is best called the:",
          choices: ["A) octave", "B) volta", "C) caesura", "D) refrain"],
          answer: "B) volta",
          hint: "The Italian word for 'turn.'",
          solution: "The volta is the argumentative turn — here delivered as a couplet reversal.",
        },
        {
          id: "li-po-2", kind: "MC",
          prompt: "'O wild West Wind, thou breath of Autumn's being' is an example of:",
          choices: ["A) apostrophe", "B) allusion", "C) irony", "D) understatement"],
          answer: "A) apostrophe",
          hint: "Direct address to something nonhuman/absent.",
          solution: "Shelley addresses the wind directly — apostrophe launching an ode.",
        },
        {
          id: "li-po-3", kind: "MC",
          prompt: "Heavy enjambment across a poem's stanzas most likely creates a sense of:",
          choices: ["A) calm resolution", "B) breathless continuity or compulsion", "C) formal detachment", "D) comic timing"],
          answer: "B) breathless continuity or compulsion",
          hint: "No full stops = no rest.",
          solution: "Run-on lines propel the reader forward, mimicking urgency or obsession.",
        },
        {
          id: "li-po-4", kind: "MC",
          prompt: "In context, a repeated refrain that changes one word each time primarily functions to:",
          choices: ["A) fill meter", "B) track the speaker's evolving state", "C) confuse the theme", "D) display rhyme skill"],
          answer: "B) track the speaker's evolving state",
          hint: "Variation within repetition = change over time.",
          solution: "The shifting word marks development — each return of the refrain measures how far the speaker has moved.",
        },
        {
          id: "li-po-5", kind: "FRQ",
          prompt: "Q1-style prompt: Read Keats's 'When I Have Fears' (sonnet). Write a thesis + first body paragraph analyzing how the octave's imagery of harvest/grain conveys anxiety about mortality and unfulfilled potential.",
          answer: "Thesis links harvest imagery to fear of dying before ripening",
          hint: "Thesis template: 'Through [devices], the speaker conveys [complex meaning] about [theme].'",
          solution: "Sample thesis: 'Through harvest imagery that figures his mind as ungarnered grain, Keats conveys the terror of dying before his genius ripens.' Body: embed 'rich garners,' 'full-ripen'd grain'; analyze ripeness = maturity, harvest = death cutting it down.",
        },
        {
          id: "li-po-6", kind: "FRQ",
          prompt: "Compare how TWO poems you've studied use a natural setting to reflect a speaker's inner state. Outline: thesis, one device per poem, and a concluding complexity point.",
          answer: "Outline with mirrored structure and complexity (settings that resist the speaker)",
          hint: "Pick poems with contrasting moves (e.g., Shelley vs. Frost).",
          solution: "Strong outlines mirror structure (setting → device → inner state per poem), then add complexity: moments where nature resists or ironizes the speaker, proving setting isn't mere backdrop.",
        },
      ],
    },
    {
      id: "prose",
      title: "Prose Fiction Analysis",
      weight: "MCQ + Essay Q2",
      concepts: [
        "Narration: point of view, reliability, free indirect discourse, focalization",
        "Characterization: direct/indirect, foil, dynamic vs. static, motivation",
        "Setting as force: social, historical, and symbolic pressures",
        "Structure: in medias res, flashback, juxtaposed scenes, pacing",
        "Dialogue and detail selection: what the narrator notices reveals theme",
      ],
      formulas: [
        "Unreliable narrator flags: contradictions, gaps, defensiveness, limited knowledge",
        "Foil = contrast character that sharpens the protagonist",
        "Free indirect style: third-person grammar + character's voice",
        "Detail → pattern → theme (track repeated images)",
        "Pacing: summary speeds up, scene slows down — slow = important",
      ],
      practice: [
        {
          id: "li-pr-1", kind: "MC",
          prompt: "A first-person narrator insists 'I am an honest man' three times while describing a theft. The reader should most likely:",
          choices: ["A) trust him completely", "B) suspect unreliability via protesting too much", "C) skip the passage", "D) assume satire of lawyers"],
          answer: "B) suspect unreliability via protesting too much",
          hint: "Unprompted repetition of a virtue claim is a classic tell.",
          solution: "Defensive repetition signals the narrator managing perception — read against his claims.",
        },
        {
          id: "li-pr-2", kind: "MC",
          prompt: "A careful, frugal side character is introduced beside a reckless heir. The side character functions as a:",
          choices: ["A) deus ex machina", "B) foil", "C) chorus", "D) red herring"],
          answer: "B) foil",
          hint: "Contrast that illuminates.",
          solution: "The foil's thrift throws the heir's recklessness into relief.",
        },
        {
          id: "li-pr-3", kind: "MC",
          prompt: "A three-page dinner scene follows thirty pages of summarized years. The pacing suggests the dinner is:",
          choices: ["A) filler", "B) thematically pivotal", "C) a printing error", "D) comic relief only"],
          answer: "B) thematically pivotal",
          hint: "Narrative slowness = significance.",
          solution: "Scene-level detail (vs. summary) marks moments the novel wants weighed carefully.",
        },
        {
          id: "li-pr-4", kind: "MC",
          prompt: "Free indirect discourse is best described as:",
          choices: ["A) dialogue in quotation marks", "B) third-person narration colored by a character's idiom", "C) an essay by the author", "D) a soliloquy"],
          answer: "B) third-person narration colored by a character's idiom",
          hint: "Think Austen: 'she' grammar, Emma's voice.",
          solution: "The narration slips into the character's diction/judgments without quote marks — intimacy plus ironic distance.",
        },
        {
          id: "li-pr-5", kind: "FRQ",
          prompt: "Q2-style prompt: A passage shows a character returning to a childhood home and noticing changed details. Write a thesis + one body paragraph on how the narrator's selection of details conveys the character's attitude toward the past.",
          answer: "Thesis: details reveal ambivalence — nostalgia laced with estrangement",
          hint: "Pair one warm detail with one alienating detail; analyze the friction.",
          solution: "Sample thesis: 'Through details that render the familiar strange — the shrunken staircase, the too-loud clock — the narration conveys estrangement beneath nostalgia.' Analyze diction ('shrunken,' 'too-loud') as perception, not objective fact.",
        },
        {
          id: "li-pr-6", kind: "FRQ",
          prompt: "Analyze a relationship in your Q3 novel: how does the author use contrast between the two characters to develop a theme? Draft two topic sentences + the evidence you'd cite.",
          answer: "Two claims with paired scenes/quotes per character",
          hint: "Structure: 'Where X does ___, Y does ___ — a contrast revealing [theme].'",
          solution: "Strong drafts pick specific paired moments (not whole-plot summaries) and name the theme the contrast serves, e.g., duty vs. desire, appearance vs. reality.",
        },
      ],
    },
    {
      id: "drama",
      title: "Drama & Shakespeare",
      weight: "MCQ + Q3 bank",
      concepts: [
        "Dramatic irony, soliloquy vs. aside, stichomythia",
        "Verse vs. prose in Shakespeare (status, sanity, sincerity signals)",
        "Tragic structure and the tragic hero; comedy's recognition scenes",
        "Stagecraft: entrances/exits, props, and blocking as meaning",
        "Reading plays as performance: tone, pacing, and audience address",
      ],
      formulas: [
        "Soliloquy = soul-talk (alone); aside = audience secret",
        "Verse → nobility/control; prose → madness, low status, or intimacy",
        "Dramatic irony = audience knows more than the character",
        "Stichomythia (rapid line-exchange) = conflict/agitation",
        "Prop tracking: objects that recur carry theme (handkerchief, daggers)",
      ],
      practice: [
        {
          id: "li-dr-1", kind: "MC",
          prompt: "The audience knows Desdemona is faithful while Othello does not. This is:",
          choices: ["A) situational irony", "B) dramatic irony", "C) sarcasm", "D) hyperbole"],
          answer: "B) dramatic irony",
          hint: "Knowledge gap between audience and character.",
          solution: "Our superior knowledge makes Othello's accusations agonizing — dramatic irony.",
        },
        {
          id: "li-dr-2", kind: "MC",
          prompt: "A nobleman suddenly speaking prose in a tense scene most likely signals:",
          choices: ["A) a printing mistake", "B) disordered mind or dropped pretense", "C) a song cue", "D) the play's end"],
          answer: "B) disordered mind or dropped pretense",
          hint: "Verse is the nobility's default; breaking it means something.",
          solution: "Prose from verse-speakers marks madness (Lear), intimacy, or plotting (Iago's prose-adjacent bluntness).",
        },
        {
          id: "li-dr-3", kind: "MC",
          prompt: "Rapid single-line exchanges between two rivals (stichomythia) primarily convey:",
          choices: ["A) harmony", "B) escalating conflict", "C) narration", "D) comic relief"],
          answer: "B) escalating conflict",
          hint: "Think verbal dueling — short, parried lines.",
          solution: "Compressed turn-taking mimics combat rhythm and rising stakes.",
        },
        {
          id: "li-dr-4", kind: "MC",
          prompt: "A handkerchief that recurs across five scenes accumulating new meanings functions as a:",
          choices: ["A) motif/symbol", "B) plot hole", "C) aside", "D) chorus"],
          answer: "A) motif/symbol",
          hint: "Recurring concrete object + shifting meaning.",
          solution: "Othello's handkerchief condenses love, proof, and honor into one trackable object.",
        },
        {
          id: "li-dr-5", kind: "FRQ",
          prompt: "Compare how Hamlet's 'To be, or not to be' soliloquy and one other soliloquy reveal different facets of his dilemma. Outline two body paragraphs with line references.",
          answer: "Contemplative-philosophical vs. self-lacerating/active facets",
          hint: "Contrast the abstract universalizing of 'To be' with the personal guilt of 'O, what a rogue.'",
          solution: "Strong outlines show range: metaphysical paralysis in one, self-disgust and resolve-building in the other — together proving his complexity.",
        },
        {
          id: "li-dr-6", kind: "FRQ",
          prompt: "Defend or challenge: 'A play cannot be fully understood by reading alone.' Use one comedy and one tragedy as evidence (200 words).",
          answer: "Argument engaging performance elements (timing, staging, audience)",
          hint: "Take a side but concede the other — that's complexity.",
          solution: "Strong answers cite performable moments (Porter's timing, the duel's staging) while conceding that close reading catches verbal patterning performance may blur.",
        },
      ],
    },
    {
      id: "essay-craft",
      title: "Essay Craft: Q1 & Q2",
      weight: "Essay 2/3",
      concepts: [
        "Thesis as arguable, specific, complexity-ready claim (not summary)",
        "Topic sentences that advance the argument, not list devices",
        "Embedding quotes: grammar, brevity, citation flow",
        "Commentary ratio: 2–3× more analysis than evidence",
        "Complexity point: counter-reading, ambiguity, or structural irony",
      ],
      formulas: [
        "Thesis = device/technique + complex meaning + theme ('Through X, ... conveys ...')",
        "CEA paragraph: Claim → Evidence (embedded) → Analysis (how/why)",
        "Quote length ≤ 2 lines; never a full sentence standing alone",
        "Sophistication = style + complexity + interpretation depth",
        "Last 5 min: check thesis match, verb tenses, quote integration",
      ],
      practice: [
        {
          id: "li-ec-1", kind: "MC",
          prompt: "Which thesis is strongest for a poetry analysis essay?",
          choices: ["A) The poem uses imagery and symbolism.", "B) Through barren winter imagery that gradually thaws, the speaker moves from grief to tentative renewal.", "C) This is a good poem about winter.", "D) The poet was sad when writing."],
          answer: "B) Through barren winter imagery that gradually thaws, the speaker moves from grief to tentative renewal.",
          hint: "Arguable + specific + traces a movement.",
          solution: "B names technique, tracks development, and claims meaning — everything a reader can debate and you can prove.",
        },
        {
          id: "li-ec-2", kind: "MC",
          prompt: "A paragraph quotes six lines, then adds one sentence: 'This shows the theme.' The main problem is:",
          choices: ["A) too many big words", "B) evidence without analysis", "C) wrong poem", "D) too short"],
          answer: "B) evidence without analysis",
          hint: "The quote-to-commentary ratio is inverted.",
          solution: "Quotes prove nothing alone; the HOW/WHY commentary earns the points.",
        },
        {
          id: "li-ec-3", kind: "MC",
          prompt: "The best way to earn the sophistication point is to:",
          choices: ["A) use ten-syllable words", "B) write five pages", "C) sustain a convincing interpretation with nuance and efficient style", "D) summarize the plot elegantly"],
          answer: "C) sustain a convincing interpretation with nuance and efficient style",
          hint: "It's awarded for through-line quality, not tricks.",
          solution: "A consistently insightful, well-controlled essay with a complexity thread earns it.",
        },
        {
          id: "li-ec-4", kind: "MC",
          prompt: "The most effective embedded quote:",
          choices: ["A) 'The author writes: [entire stanza].'", "B) The 'sullen' house 'bit back' against the wind", "C) A quote with no context at all", "D) A paraphrase labeled as a quote"],
          answer: "B) The 'sullen' house 'bit back' against the wind",
          hint: "Short, grammatical, blended into your own sentence.",
          solution: "B weaves fragments into the writer's syntax — smooth and precise.",
        },
        {
          id: "li-ec-5", kind: "FRQ",
          prompt: "Rewrite this weak thesis three ways, each adding complexity: 'The story uses symbolism to show love is hard.'",
          answer: "Three specific, arguable theses with device + tension",
          hint: "Name the symbol, name the two-sided truth about love.",
          solution: "Example: 'Through the recurring locked garden — cultivated yet inaccessible — the narrative figures love as labor that excludes even as it invites.' Each rewrite should add a named device and a both/and claim.",
        },
        {
          id: "li-ec-6", kind: "FRQ",
          prompt: "Take one body paragraph you wrote this week. Revise it to double the commentary: add a 'this matters because' sentence and a counter-reading sentence.",
          answer: "Revised paragraph with extended analysis + acknowledged alternative",
          hint: "'A skeptical reader might object that... Yet...'",
          solution: "Revisions should show the ratio shift: same evidence, deeper unpacking, plus a conceded-and-answered objection for complexity.",
        },
      ],
    },
    {
      id: "literary-argument",
      title: "Q3: The Literary Argument",
      weight: "Essay 1/3",
      concepts: [
        "Choosing the right work: know 4+ texts across genres deeply",
        "Reading the prompt for the abstract claim (not just the question)",
        "Selecting 2–3 scenes/devices that prove the claim in your work",
        "Universalizing: from textual evidence to the larger meaning",
        "Pre-writing 4 work profiles: themes, scenes, devices, quotes",
      ],
      formulas: [
        "Work bank: 1 Shakespeare + 1 19th-c. novel + 1 modern + 1 wildcard",
        "Per work: 3 themes, 3 key scenes, 2 devices, 2 quotes",
        "Structure: intro + 2–3 evidence paragraphs + complexity close",
        "Never summarize plot — argue with moments",
        "Complexity: 'even within this, the novel qualifies...'",
      ],
      practice: [
        {
          id: "li-q3-1", kind: "MC",
          prompt: "The Q3 prompt asks about 'a character who resists social expectations.' Your first move should be to:",
          choices: ["A) summarize your novel's plot", "B) pick the work whose character best fits, then select proving scenes", "C) define 'society' from a dictionary", "D) write about yourself"],
          answer: "B) pick the work whose character best fits, then select proving scenes",
          hint: "Fit first, then evidence — argument over summary.",
          solution: "Choose the strongest-fit work, then build the case from specific moments.",
        },
        {
          id: "li-q3-2", kind: "MC",
          prompt: "Which work-bank spread is safest?",
          choices: ["A) four Marvel movies", "B) Hamlet, Jane Eyre, Beloved, The Great Gatsby", "C) four poems by one author", "D) a memoir you half-remember"],
          answer: "B) Hamlet, Jane Eyre, Beloved, The Great Gatsby",
          hint: "Range across era, genre, and theme = prompt-proof.",
          solution: "Diverse canonical works cover most abstract claims; films/memoirs risk prompt mismatch.",
        },
        {
          id: "li-q3-3", kind: "MC",
          prompt: "A Q3 essay that retells the whole novel scores poorly mainly because it:",
          choices: ["A) is too long", "B) substitutes summary for argument", "C) uses present tense", "D) mentions the author"],
          answer: "B) substitutes summary for argument",
          hint: "The rubric rewards selecting evidence for a claim.",
          solution: "Moments chosen to prove a thesis beat comprehensive retelling.",
        },
        {
          id: "li-q3-4", kind: "MC",
          prompt: "The fastest in-exam test that a chosen work fits the prompt is:",
          choices: ["A) you like it", "B) you can name 2–3 specific scenes proving the claim in 60 seconds", "C) it's long", "D) your teacher taught it"],
          answer: "B) you can name 2–3 specific scenes proving the claim in 60 seconds",
          hint: "Evidence availability = fit.",
          solution: "If scenes don't come instantly, switch works before writing.",
        },
        {
          id: "li-q3-5", kind: "FRQ",
          prompt: "Prompt: 'Many works show a character torn between loyalty and self-interest. Select a work...' — Write a full thesis + two scene-based topic sentences for YOUR chosen work.",
          answer: "Thesis with named scenes and the both/and tension",
          hint: "Name the scenes in the thesis itself for control.",
          solution: "Example (Gatsby): 'Through Gatsby's curated parties and his final solitary funeral, Fitzgerald argues loyalty curdles into self-interest when identity is performance.' Each topic sentence should advance, not repeat, the thesis.",
        },
        {
          id: "li-q3-6", kind: "FRQ",
          prompt: "Build one work profile now: pick a novel/play, list 3 themes, 3 key scenes (with 1 quote each), and 2 recurring devices. Keep it on one page for exam-week review.",
          answer: "One-page profile completed",
          hint: "Choose the work you know best, not the most impressive one.",
          solution: "Profiles convert vague familiarity into retrievable evidence — the single highest-ROI Q3 prep task.",
        },
      ],
    },
  ],
};
