import type { Subject } from "./types";

export const calcbc: Subject = {
  id: "calc-bc",
  name: "AP Calculus BC",
  short: "Calc BC",
  tagline: "Limits, differentiation, integration, series & parametric/polar",
  color: "#7c3aed",
  soft: "#ede9fe",
  exam: {
    format: "3h 15m · 45 MCQ (50%) + 6 FRQ (50%)",
    mcq: "45 multiple-choice, 105 min — Part A no calculator (30), Part B calculator (15)",
    frq: "6 free-response, 90 min — at least 2 calculator-active; answers to 3 decimals, show setup",
  },
  tips: [
    "FRQ setup first: write the integral/derivative expression before touching the calculator — setup points survive arithmetic slips.",
    "Memorize the Big Five series (e^x, sin x, cos x, 1/(1−x), ln(1+x)) with radii; half of series FRQs reduce to substitution.",
    "Units and 'justify' discipline: every max/min claim needs sign analysis or First Derivative Test reference.",
    "Calculator fluency: practice fnInt, numeric derivative, and root-finding so Part B is pure speed.",
    "Three-decimal rule: never round intermediate steps; only the final answer, and keep supporting work exact.",
  ],
  units: [
    {
      id: "limits",
      title: "Limits & Continuity",
      weight: "4–7%",
      concepts: [
        "Estimating limits from graphs and tables; one-sided limits",
        "Algebraic techniques: factoring, conjugates, common denominators",
        "Squeeze theorem and special trig limits (sin x / x)",
        "Infinite limits and limits at infinity; horizontal/vertical asymptotes",
        "Continuity: definition, types of discontinuity, Intermediate Value Theorem",
      ],
      formulas: [
        "lim(x→0) sin x / x = 1; lim(x→0) (1 − cos x)/x = 0",
        "Continuous at a: limit exists and equals f(a)",
        "IVT: continuous on [a,b] attains every value between f(a), f(b)",
        "Horizontal asymptotes via dominant terms / degrees",
        "Removable vs. jump vs. infinite discontinuities",
      ],
      practice: [
        {
          id: "ca-li-1", kind: "MC",
          prompt: "lim(x→3) (x² − 9)/(x − 3) equals:",
          choices: ["A) 0", "B) 3", "C) 6", "D) DNE"],
          answer: "C) 6",
          hint: "Factor the numerator first.",
          solution: "(x−3)(x+3)/(x−3) = x+3 → 6.",
        },
        {
          id: "ca-li-2", kind: "MC",
          prompt: "lim(x→∞) (4x³ − 2x + 1)/(2x³ + 5x²) equals:",
          choices: ["A) 0", "B) 2", "C) 4", "D) ∞"],
          answer: "B) 2",
          hint: "Ratio of leading coefficients for equal degrees.",
          solution: "4/2 = 2.",
        },
        {
          id: "ca-li-3", kind: "MC",
          prompt: "f(x) = (x²−1)/(x−1) for x ≠ 1, f(1) = 1. At x = 1, f is:",
          choices: ["A) continuous", "B) removable discontinuity", "C) jump discontinuity", "D) differentiable"],
          answer: "B) removable discontinuity",
          hint: "Limit is 2 but f(1) = 1.",
          solution: "Limit 2 ≠ value 1 — a hole that redefining f(1) = 2 would fix.",
        },
        {
          id: "ca-li-4", kind: "MC",
          prompt: "Given f continuous on [1,4] with f(1) = 3, f(4) = 10, IVT guarantees:",
          choices: ["A) f has a maximum at x = 4", "B) some c in (1,4) with f(c) = 7", "C) f is differentiable", "D) f(c) = 7 twice"],
          answer: "B) some c in (1,4) with f(c) = 7",
          hint: "7 lies between 3 and 10.",
          solution: "IVT promises at least one c with f(c) = 7 — existence, not count or location.",
        },
        {
          id: "ca-li-5", kind: "FRQ",
          prompt: "Let f(x) = (√(x+1) − 2)/(x − 3). (a) Evaluate lim(x→3) f(x) showing work. (b) Is f continuous at x = 3? Justify. (c) What value would make the extended function continuous?",
          answer: "(a) 1/4; (b) no — undefined; (c) 1/4",
          hint: "Multiply by the conjugate of the numerator.",
          solution: "(a) ×(√(x+1)+2)/(√(x+1)+2) → 1/(√(x+1)+2) → 1/4. (b) Not continuous: f(3) undefined (0/0). (c) Define f(3) = 1/4 to remove the discontinuity.",
        },
        {
          id: "ca-li-6", kind: "FRQ",
          prompt: "Use the Squeeze Theorem to prove lim(x→0) x²·sin(1/x) = 0, and explain why direct substitution fails.",
          answer: "Bounded oscillation squeezed by x² → 0",
          hint: "−1 ≤ sin(1/x) ≤ 1, then multiply through by x².",
          solution: "−x² ≤ x²sin(1/x) ≤ x²; both bounds → 0, so the middle → 0. Direct substitution gives 0·(undefined oscillation) — indeterminate form requiring the squeeze.",
        },
      ],
    },
    {
      id: "differentiation",
      title: "Differentiation: Rules & Meaning",
      weight: "10–13%",
      concepts: [
        "Definition of the derivative; tangent-line and linear approximation",
        "Power, product, quotient, and chain rules",
        "Derivatives of trig, inverse trig, exponential, logarithmic functions",
        "Implicit differentiation; derivatives of inverse functions",
        "Related rates and L'Hôpital's rule (BC)",
      ],
      formulas: [
        "(uv)′ = u′v + uv′; (u/v)′ = (u′v − uv′)/v²",
        "d/dx sin⁻¹x = 1/√(1−x²); d/dx tan⁻¹x = 1/(1+x²)",
        "d/dx aˣ = aˣ ln a; d/dx ln x = 1/x",
        "L(x) = f(a) + f′(a)(x − a)",
        "L'Hôpital: 0/0 or ∞/∞ → differentiate top and bottom",
      ],
      practice: [
        {
          id: "ca-df-1", kind: "MC",
          prompt: "d/dx [x³·sin x] equals:",
          choices: ["A) 3x²·cos x", "B) 3x² sin x + x³ cos x", "C) 3x² sin x − x³ cos x", "D) x³ cos x"],
          answer: "B) 3x² sin x + x³ cos x",
          hint: "Product rule.",
          solution: "(3x²)(sin x) + (x³)(cos x).",
        },
        {
          id: "ca-df-2", kind: "MC",
          prompt: "d/dx tan⁻¹(2x) equals:",
          choices: ["A) 2/(1+4x²)", "B) 1/(1+4x²)", "C) 2/√(1−4x²)", "D) sec²(2x)"],
          answer: "A) 2/(1+4x²)",
          hint: "Chain rule on arctan(u).",
          solution: "[1/(1+(2x)²)]·2 = 2/(1+4x²).",
        },
        {
          id: "ca-df-3", kind: "MC",
          prompt: "lim(x→0) (eˣ − 1 − x)/x² equals:",
          choices: ["A) 0", "B) 1/2", "C) 1", "D) 2"],
          answer: "B) 1/2",
          hint: "Apply L'Hôpital twice (0/0 both times).",
          solution: "→ (eˣ−1)/2x → eˣ/2 → 1/2.",
        },
        {
          id: "ca-df-4", kind: "MC",
          prompt: "If x² + y² = 25, dy/dx at (3, 4) is:",
          choices: ["A) −3/4", "B) 3/4", "C) −4/3", "D) 4/3"],
          answer: "A) −3/4",
          hint: "Implicit: 2x + 2y·y′ = 0.",
          solution: "y′ = −x/y = −3/4.",
        },
        {
          id: "ca-df-5", kind: "FRQ",
          prompt: "A 13-ft ladder slides: top at height y, bottom at distance x from wall. When x = 5 ft, dx/dt = 2 ft/s. (a) Find dy/dt. (b) Is the top speeding up or slowing in descent? Justify with a second-derivative or rate argument.",
          answer: "(a) −5/6 ft/s ≈ −0.833 ft/s",
          hint: "x² + y² = 169; differentiate implicitly.",
          solution: "(a) y = 12; 2x·x′ + 2y·y′ = 0 → y′ = −(5·2)/12 = −5/6 ft/s. (b) As y shrinks, |y′| = xx′/y grows → the descent accelerates.",
        },
        {
          id: "ca-df-6", kind: "FRQ",
          prompt: "Let f(x) = x·e^(−x²). (a) Find f′ and its critical points. (b) Write the tangent line at x = 1 and use it to approximate f(1.1). (c) Is the approximation an over- or underestimate near x = 1? Justify with concavity.",
          answer: "(a) f′ = e^(−x²)(1−2x²), crit ±1/√2; (b) y − 1/e = −(1/e)(x−1)",
          hint: "Product rule with chain rule on the exponential.",
          solution: "(a) f′ = e^(−x²) − 2x²e^(−x²) = e^(−x²)(1−2x²) = 0 at x = ±1/√2. (b) f(1) = 1/e, f′(1) = −1/e → L = (1/e)(2−x); f(1.1) ≈ 0.9/e ≈ 0.331. (c) f′′(1) < 0 (concave down) → tangent overestimates.",
        },
      ],
    },
    {
      id: "applications-deriv",
      title: "Applications of Differentiation",
      weight: "8–11%",
      concepts: [
        "Mean Value Theorem and Rolle's theorem hypotheses",
        "First and Second Derivative Tests; critical points and inflection",
        "Curve sketching: increasing/decreasing, concavity, asymptotes",
        "Optimization: setting up, domain endpoints, justification",
        "Motion: position/velocity/acceleration; speed vs. velocity",
      ],
      formulas: [
        "MVT: some c with f′(c) = (f(b)−f(a))/(b−a)",
        "f′ > 0 increasing; f′′ > 0 concave up",
        "Candidates test for global extrema on closed intervals",
        "v = s′, a = v′; speed = |v|; speeding up when v,a same sign",
        "Inflection: f′′ changes sign",
      ],
      practice: [
        {
          id: "ca-ad-1", kind: "MC",
          prompt: "f′ changes from + to − at x = 2. Then f(2) is a:",
          choices: ["A) local minimum", "B) local maximum", "C) inflection point", "D) cusp"],
          answer: "B) local maximum",
          hint: "First Derivative Test.",
          solution: "Rising then falling → local max.",
        },
        {
          id: "ca-ad-2", kind: "MC",
          prompt: "A particle's v(t) = t² − 4t + 3 on [0,5]. It is moving left on:",
          choices: ["A) (1,3)", "B) (0,1)∪(3,5)", "C) (3,5)", "D) never"],
          answer: "A) (1,3)",
          hint: "Factor: (t−1)(t−3); left means v < 0.",
          solution: "Parabola opening up, negative between roots 1 and 3.",
        },
        {
          id: "ca-ad-3", kind: "MC",
          prompt: "f(x) = x³ − 3x². Inflection point at:",
          choices: ["A) x = 0", "B) x = 1", "C) x = 2", "D) none"],
          answer: "B) x = 1",
          hint: "f′′ = 6x − 6; check sign change.",
          solution: "f′′ = 0 at x = 1, negative left, positive right → inflection.",
        },
        {
          id: "ca-ad-4", kind: "MC",
          prompt: "MVT applies to f on [0,4] if f is:",
          choices: ["A) continuous on [0,4] and differentiable on (0,4)", "B) differentiable only at endpoints", "C) discontinuous inside", "D) any function"],
          answer: "A) continuous on [0,4] and differentiable on (0,4)",
          hint: "State the hypotheses exactly.",
          solution: "Continuity on closed + differentiability on open interval.",
        },
        {
          id: "ca-ad-5", kind: "FRQ",
          prompt: "A farmer has 400 m of fencing for a rectangular pen against a barn (no fence on barn side). (a) Maximize the area; justify the optimum. (b) State dimensions and max area.",
          answer: "50 m out × 200 m along barn; 10,000 m²",
          hint: "A = x(400 − 2x).",
          solution: "(a) A′ = 400 − 4x = 0 → x = 100, length 200; A′′ = −4 < 0 → max. Dimensions 100 m × 200 m, area 20,000 m².",
        },
        {
          id: "ca-ad-6", kind: "FRQ",
          prompt: "Given f′ graph (parabola opening up, zeros at x = 1 and x = 5, vertex below axis): (a) intervals of increase/decrease, (b) x-values of extrema with justification, (c) where f is concave up given f′′ signs implied.",
          answer: "Increase on (−∞,1)∪(5,∞); local max at 1, min at 5",
          hint: "f′ > 0 (above axis) means f increases.",
          solution: "(a) f′ > 0 outside [1,5] → increasing there; decreasing on (1,5). (b) +→− at x = 1 → local max; −→+ at 5 → local min (First Derivative Test). (c) f increasing-steeper... concave up where f′ increases: left of vertex (x < 3).",
        },
      ],
    },
    {
      id: "integration",
      title: "Integration & Accumulation",
      weight: "12–15%",
      concepts: [
        "Riemann sums (left/right/midpoint/trapezoid) and definite integral as net area",
        "Fundamental Theorem: d/dx ∫ₐˣ f = f(x); Net Change Theorem",
        "Antiderivatives; u-substitution; integration by parts (BC)",
        "Partial fractions and improper integrals (BC)",
        "Accumulation functions and motion: displacement vs. total distance",
      ],
      formulas: [
        "∫ xⁿ dx = xⁿ⁺¹/(n+1); ∫ eˣ = eˣ; ∫ 1/x = ln|x|",
        "u-sub: ∫ f(g(x))g′(x)dx = ∫ f(u)du",
        "Parts: ∫ u dv = uv − ∫ v du (LIATE)",
        "Trapezoid error bound: |E| ≤ K(b−a)³/(12n²)",
        "Distance = ∫|v|; displacement = ∫v",
      ],
      practice: [
        {
          id: "ca-in-1", kind: "MC",
          prompt: "∫(2x + 3/x)dx equals:",
          choices: ["A) x² + 3 ln|x| + C", "B) 2x² + 3 ln|x| + C", "C) x² + 3/x² + C", "D) 2 + 3 ln|x| + C"],
          answer: "A) x² + 3 ln|x| + C",
          hint: "Integrate term by term.",
          solution: "x² + 3ln|x| + C.",
        },
        {
          id: "ca-in-2", kind: "MC",
          prompt: "d/dx ∫₂ˣ √(1+t³) dt equals:",
          choices: ["A) √(1+x³)", "B) (3x²)/(2√(1+x³))", "C) 0", "D) √(1+8)"],
          answer: "A) √(1+x³)",
          hint: "FTC Part 1 directly.",
          solution: "Derivative of the accumulation = integrand at x.",
        },
        {
          id: "ca-in-3", kind: "MC",
          prompt: "∫₁^e (ln x)/x dx equals:",
          choices: ["A) 0", "B) 1/2", "C) 1", "D) e"],
          answer: "B) 1/2",
          hint: "u = ln x.",
          solution: "∫₀¹ u du = 1/2.",
        },
        {
          id: "ca-in-4", kind: "MC",
          prompt: "v(t) = 3t − 2 on [0,4]. Total distance traveled is:",
          choices: ["A) 16", "B) 40/3 ≈ 13.3", "C) 56/3 ≈ 18.67", "D) 8"],
          answer: "B) 40/3 ≈ 13.3",
          hint: "Split at t = 2/3 where v = 0; integrate |v|.",
          solution: "|∫₀^{2/3}| + |∫_{2/3}⁴| = 2/3 + 38/3 = 40/3.",
        },
        {
          id: "ca-in-5", kind: "FRQ",
          prompt: "Evaluate ∫ x·e^(x²) dx and ∫₀¹ x·e^(x²) dx. Then evaluate ∫₀¹ x²·eˣ dx using integration by parts twice (show both steps).",
          answer: "(a) ½e^(x²)+C; (b) (e−1)/2; (c) e − 2",
          hint: "u = x² for the first; LIATE → u = x² for parts.",
          solution: "(a) u = x² → ½∫e^u du = ½e^(x²)+C. (b) ½(e−1). (c) x²eˣ|₀¹ − 2∫xeˣ = e − 2(xeˣ−eˣ)|₀¹ = e − 2(1) = e−2.",
        },
        {
          id: "ca-in-6", kind: "FRQ",
          prompt: "Determine whether ∫₁^∞ (1/x²)dx converges and to what value; then argue why ∫₁^∞ (1/x)dx diverges. (Show limit work.)",
          answer: "Converges to 1; harmonic diverges (ln b → ∞)",
          hint: "Integrate to b, then let b → ∞.",
          solution: "∫₁ᵇ x⁻² = 1 − 1/b → 1. ∫₁ᵇ 1/x = ln b → ∞, so diverges.",
        },
      ],
    },
    {
      id: "diff-eq",
      title: "Differential Equations & Slope Fields",
      weight: "6–8%",
      concepts: [
        "Slope fields: matching equations to fields, sketching solution curves",
        "Separable equations: dy/dx = f(x)g(y) workflow",
        "Particular solutions with initial conditions; domain restrictions",
        "Exponential models: dy/dt = ky; logistic growth (BC)",
        "Euler's method for numerical approximation (BC)",
      ],
      formulas: [
        "Separate: dy/g(y) = f(x)dx, integrate, +C, solve",
        "y = Ce^(kt) solves dy/dt = ky",
        "Logistic: dP/dt = kP(1 − P/M); carrying capacity M",
        "Euler: yₙ₊₁ = yₙ + h·F(xₙ, yₙ)",
      ],
      practice: [
        {
          id: "ca-de-1", kind: "MC",
          prompt: "dy/dx = x/y, y(0) = 2. The particular solution is:",
          choices: ["A) y = x²/2 + 2", "B) y = √(x²+4)", "C) y = x² + 4", "D) y = eˣ + 1"],
          answer: "B) y = √(x²+4)",
          hint: "y dy = x dx → y²/2 = x²/2 + C.",
          solution: "y² = x² + C; 4 = C → y = √(x²+4) (positive branch by IC).",
        },
        {
          id: "ca-de-2", kind: "MC",
          prompt: "A slope field for dy/dx = y(1 − y/10) has equilibrium solutions:",
          choices: ["A) y = 0 only", "B) y = 0 and y = 10", "C) y = 1 only", "D) none"],
          answer: "B) y = 0 and y = 10",
          hint: "Set the right side to zero.",
          solution: "y = 0 (unstable) and y = 10 = carrying capacity (stable).",
        },
        {
          id: "ca-de-3", kind: "MC",
          prompt: "Using Euler with h = 0.5 for dy/dx = x + y, (x₀,y₀) = (0,1): y₁ is:",
          choices: ["A) 1.0", "B) 1.5", "C) 2.0", "D) 0.5"],
          answer: "B) 1.5",
          hint: "y₁ = 1 + 0.5(0 + 1).",
          solution: "1 + 0.5 = 1.5.",
        },
        {
          id: "ca-de-4", kind: "MC",
          prompt: "A slope field shows horizontal segments along y = 2 for dy/dx = ky − 4. Then k is:",
          choices: ["A) 0", "B) −2", "C) 2", "D) 4"],
          answer: "C) 2",
          hint: "Equilibrium where ky − 4 = 0.",
          solution: "Equilibrium where ky − 4 = 0 → y = 4/k = 2 gives k = 2.",
        },
        {
          id: "ca-de-5", kind: "FRQ",
          prompt: "Solve dy/dx = (x+1)/y² with y(0) = 1. Give the particular solution and state the largest interval containing x = 0 where it is valid.",
          answer: "y = ∛((3x²+6x+2)/2 ... ) — y³ = (3/2)x²+3x+1",
          hint: "y² dy = (x+1)dx.",
          solution: "y³/3 = x²/2 + x + C; IC: 1/3 = C → y³ = (3/2)x² + 3x + 1; valid where RHS > 0 around x = 0 (between its real roots).",
        },
        {
          id: "ca-de-6", kind: "FRQ",
          prompt: "Bacteria follow dP/dt = 0.3P with P(0) = 200. (a) Solve for P(t). (b) When does the population reach 2000? (c) If instead logistic with capacity 5000, describe the long-run behavior and how the graph differs.",
          answer: "(a) 200e^(0.3t); (b) t = ln10/0.3 ≈ 7.7",
          hint: "Unrestricted growth: exponential; doubling view via ln.",
          solution: "(a) P = 200e^0.3t. (b) 10 = e^0.3t → t ≈ 7.68. (c) Logistic levels off at 5000 (horizontal asymptote); S-curve vs. unbounded exponential.",
        },
      ],
    },
    {
      id: "area-volume",
      title: "Applications of Integration",
      weight: "8–11%",
      concepts: [
        "Area between curves: top − bottom (or right − left)",
        "Volumes: disk/washer (rotation) and cross-section methods",
        "Volumes with known cross sections (squares, semicircles, triangles)",
        "Arc length and BC density/average-value problems",
        "Setting up before integrating: sketch, bounds, radius expressions",
      ],
      formulas: [
        "A = ∫(top − bottom)dx",
        "Disk: V = π∫R²; Washer: π∫(R² − r²)",
        "Cross sections: V = ∫A(x)dx",
        "Average value: (1/(b−a))∫ₐᵇ f",
        "Arc length: ∫√(1 + (dy/dx)²)dx",
      ],
      practice: [
        {
          id: "ca-av-1", kind: "MC",
          prompt: "Area between y = x and y = x² from 0 to 1 is:",
          choices: ["A) 1/6", "B) 1/3", "C) 1/2", "D) 1"],
          answer: "A) 1/6",
          hint: "∫₀¹ (x − x²)dx.",
          solution: "1/2 − 1/3 = 1/6.",
        },
        {
          id: "ca-av-2", kind: "MC",
          prompt: "Region under y = √x from 0 to 4 rotated about the x-axis. Volume is:",
          choices: ["A) 4π", "B) 8π", "C) 16π", "D) 32π/3"],
          answer: "B) 8π",
          hint: "Disks: π∫₀⁴ x dx.",
          solution: "π[x²/2]₀⁴ = 8π.",
        },
        {
          id: "ca-av-3", kind: "MC",
          prompt: "Base bounded by y = x² and y = 4; cross sections perpendicular to x-axis are squares. Volume equals:",
          choices: ["A) ∫₋₂² (4−x²)² dx", "B) π∫₋₂² (4−x²)² dx", "C) ∫₋₂² (4−x²) dx", "D) ∫₀⁴ (4−x²)² dx"],
          answer: "A) ∫₋₂² (4−x²)² dx",
          hint: "Side length = top − bottom; no π for squares.",
          solution: "V = ∫s² = ∫₋₂² (4−x²)² dx.",
        },
        {
          id: "ca-av-4", kind: "MC",
          prompt: "Average value of f(x) = 3x² on [1,3] is:",
          choices: ["A) 9", "B) 13", "C) 26", "D) 8"],
          answer: "B) 13",
          hint: "(1/2)∫₁³ 3x² dx = (1/2)(27−1).",
          solution: "26/2 = 13.",
        },
        {
          id: "ca-av-5", kind: "FRQ",
          prompt: "Region R enclosed by y = eˣ, y = 1, x = 2. (a) Find its area. (b) Write (do not evaluate) the washer integral for rotation about y = −1. (c) Write the integral for rotation about the y-axis using shells.",
          answer: "(a) e² − 3 ≈ 4.389",
          hint: "Area: ∫₀² (eˣ − 1)dx.",
          solution: "(a) [eˣ − x]₀² = e² − 3. (b) π∫₀²[(eˣ+1)² − 2²]dx. (c) 2π∫₀² x(eˣ−1)dx.",
        },
        {
          id: "ca-av-6", kind: "FRQ",
          prompt: "Explain how to choose between disk/washer and shell methods for a volume problem, using rotation of y = x² (0 ≤ x ≤ 2) about the y-axis as your example.",
          answer: "Shells natural (dx, radius x); washers need inverse functions",
          hint: "dx slices give shells around the y-axis directly.",
          solution: "Shells: 2π∫₀² x·x² dx — one integral, no inversion. Washers need x = √y plus splitting (gap below vertex region handled carefully). Rule: match slice orientation to the method that avoids inversion/splitting.",
        },
      ],
    },
    {
      id: "parametric",
      title: "Parametric, Polar & Vector",
      weight: "8–11% (BC only)",
      concepts: [
        "Parametric derivatives: dy/dx = (dy/dt)/(dx/dt); second derivatives",
        "Parametric arc length and speed; motion direction along curves",
        "Polar coordinates: conversion, graphing cardioids/roses/limacons",
        "Polar area: (1/2)∫r² dθ; slope in polar form",
        "Vector-valued functions: velocity, acceleration, speed, distance",
      ],
      formulas: [
        "dy/dx = y′(t)/x′(t)",
        "L = ∫√((x′)² + (y′)²)dt; speed = √((x′)²+(y′)²)",
        "x = r cosθ, y = r sinθ; r² = x² + y²",
        "A_polar = (1/2)∫ r² dθ",
        "dy/dx polar = (r′sinθ + rcosθ)/(r′cosθ − rsinθ)",
      ],
      practice: [
        {
          id: "ca-pa-1", kind: "MC",
          prompt: "x = t², y = t³ − 3t. dy/dx at t = 2 is:",
          choices: ["A) 9/4", "B) 9", "C) 3", "D) 12"],
          answer: "A) 9/4",
          hint: "(3t²−3)/(2t) at t = 2.",
          solution: "9/4.",
        },
        {
          id: "ca-pa-2", kind: "MC",
          prompt: "Polar curve r = 2 + 2cosθ is a:",
          choices: ["A) circle", "B) cardioid", "C) 4-petaled rose", "D) line"],
          answer: "B) cardioid",
          hint: "a + a·cosθ form.",
          solution: "Equal constants → heart-shaped cardioid.",
        },
        {
          id: "ca-pa-3", kind: "MC",
          prompt: "Area of one loop of r = 3sin(2θ) equals:",
          choices: ["A) 9π/8", "B) 9π/4", "C) 9π/2", "D) 9π"],
          answer: "A) 9π/8",
          hint: "One loop spans π/2; (1/2)∫9sin²(2θ).",
          solution: "(9/2)·(π/4) = 9π/8.",
        },
        {
          id: "ca-pa-4", kind: "MC",
          prompt: "Particle with v(t) = ⟨2t, 3t²⟩. Speed at t = 1 is:",
          choices: ["A) 5", "B) √13", "C) √10", "D) 13"],
          answer: "B) √13",
          hint: "|v| = √(4t² + 9t⁴) at t = 1.",
          solution: "√(4+9) = √13.",
        },
        {
          id: "ca-pa-5", kind: "FRQ",
          prompt: "Curve: x = 2cos t, y = 2sin t + t, 0 ≤ t ≤ 2π. (a) Find dy/dx as a function of t and evaluate at t = π/2. (b) Find the arc length setup and speed. (c) Describe the motion direction as t increases.",
          answer: "(a) dy/dx = (2cos t + 1)/(−2sin t); at π/2: −1/2",
          hint: "x′ = −2sin t, y′ = 2cos t + 1.",
          solution: "(a) (2cos t+1)/(−2sin t); at π/2 → (0+1)/(−2) = −1/2. (b) L = ∫₀^{2π}√(4sin²t + (2cos t+1)²)dt; speed = integrand. (c) Counterclockwise drift upward (circle plus rising center).",
        },
        {
          id: "ca-pa-6", kind: "FRQ",
          prompt: "Find the area inside r = 3cosθ (a circle). Show the θ-bounds you use and evaluate (1/2)∫r² dθ.",
          answer: "9π/4",
          hint: "Circle traced for θ ∈ [−π/2, π/2] (or [0,π]).",
          solution: "(1/2)∫_{−π/2}^{π/2} 9cos²θ dθ = (9/2)(π/2) = 9π/4.",
        },
      ],
    },
    {
      id: "series",
      title: "Infinite Series (BC)",
      weight: "12–15% (BC only)",
      concepts: [
        "Convergence tests: nth-term, integral, comparison, limit comparison, ratio, root, alternating",
        "Absolute vs. conditional convergence",
        "Taylor and Maclaurin series; Big Five + substitution/differentiation/integration",
        "Lagrange error bound and alternating-series remainder",
        "Radius and interval of convergence; testing endpoints",
      ],
      formulas: [
        "eˣ = Σ xⁿ/n!; sin x = Σ (−1)ⁿx²ⁿ⁺¹/(2n+1)!; cos x = Σ (−1)ⁿx²ⁿ/(2n)!",
        "1/(1−x) = Σ xⁿ (|x|<1); ln(1+x) = Σ (−1)ⁿxⁿ⁺¹/(n+1)",
        "Ratio test: L < 1 converges; L > 1 diverges",
        "|R_n| ≤ |next term| (alternating); Lagrange: |R_n| ≤ M|x−a|ⁿ⁺¹/(n+1)!",
      ],
      practice: [
        {
          id: "ca-se-1", kind: "MC",
          prompt: "Σ 1/n² converges by:",
          choices: ["A) divergence test", "B) p-series with p = 2 > 1", "C) ratio test only", "D) it diverges"],
          answer: "B) p-series with p = 2 > 1",
          hint: "p-series: converges iff p > 1.",
          solution: "p = 2 > 1 → converges.",
        },
        {
          id: "ca-se-2", kind: "MC",
          prompt: "Σ (−1)ⁿ/n (alternating harmonic) is:",
          choices: ["A) absolutely convergent", "B) conditionally convergent", "C) divergent", "D) geometric"],
          answer: "B) conditionally convergent",
          hint: "AST converges; harmonic diverges absolutely.",
          solution: "Decreasing to 0 → converges by AST; Σ1/n diverges → conditional.",
        },
        {
          id: "ca-se-3", kind: "MC",
          prompt: "Radius of convergence of Σ xⁿ/n! is:",
          choices: ["A) 0", "B) 1", "C) ∞", "D) e"],
          answer: "C) ∞",
          hint: "Ratio test: L = 0 for all x.",
          solution: "eˣ series converges everywhere.",
        },
        {
          id: "ca-se-4", kind: "MC",
          prompt: "Maclaurin polynomial of degree 2 for e^(3x) is:",
          choices: ["A) 1 + 3x + (9/2)x²", "B) 1 + x + x²/2", "C) 1 + 3x + 3x²", "D) x + 3x²"],
          answer: "A) 1 + 3x + (9/2)x²",
          hint: "Substitute 3x into e^u ≈ 1 + u + u²/2.",
          solution: "1 + 3x + 9x²/2.",
        },
        {
          id: "ca-se-5", kind: "FRQ",
          prompt: "Consider Σ (2ⁿ)/(n!). (a) Apply the ratio test and conclude. (b) Write the first three nonzero terms of the Taylor series for e^(2x) and use them to approximate e^0.2, then bound the error with the Lagrange bound (or alternating reasoning if applicable).",
          answer: "(a) L = 0 → converges; (b) ≈ 1.48",
          hint: "Ratio: [2ⁿ⁺¹/(n+1)!]·[n!/2ⁿ] = 2/(n+1).",
          solution: "(a) L = 0 < 1 → absolutely convergent. (b) 1 + 2x + 2x² → at x = 0.1: 1.22... note e^0.2 ≈ 1.221; Lagrange remainder bounds the small tail.",
        },
        {
          id: "ca-se-6", kind: "FRQ",
          prompt: "Find the interval of convergence of Σ (x−1)ⁿ/(n·2ⁿ). Show the ratio work and test both endpoints explicitly.",
          answer: "[−1, 3): converges conditionally at −1, diverges (harmonic) at 3",
          hint: "Ratio gives |x−1| < 2; endpoints: harmonic vs. alternating harmonic.",
          solution: "R = 2, center 1. At x = 3: Σ1/n diverges (harmonic). At x = −1: Σ(−1)ⁿ/n converges conditionally (AST). Interval: [−1, 3).",
        },
      ],
    },
  ],
};
