import type { Subject } from "./types";

export const physics2: Subject = {
  id: "physics2",
  name: "AP Physics 2",
  short: "Physics 2",
  tagline: "Algebra-based fluids, thermo, E&M, optics & modern physics",
  color: "#0284c7",
  soft: "#e0f2fe",
  exam: {
    format: "3 hrs · 50 MCQ (50%) + 4 FRQ (50%)",
    mcq: "50 multiple-choice, 90 min — single-select and multi-select sets",
    frq: "4 free-response: experimental design, qualitative/quantitative translation, paragraph argument, short answer",
  },
  tips: [
    "Multi-select MCQ: you must pick ALL correct options for credit — when torn, re-check units and limiting cases.",
    "FRQ paragraph arguments follow Claim → Evidence (equation) → Reasoning. Always name the principle first.",
    "Draw the field/circuit/ray diagram even when not asked — graders award setup credit and it prevents sign errors.",
    "Keep a units checklist: ρgh vs ½ρv², kQ/r vs kQ/r², Φ = BA cosθ. Dimensional analysis catches most algebra slips.",
    "For experimental-design FRQs, state the measured vs. controlled variables and exactly how the slope/intercept gives the target quantity.",
  ],
  units: [
    {
      id: "fluids",
      title: "Fluids: Statics & Dynamics",
      weight: "10–12%",
      concepts: [
        "Density ρ = m/V and pressure P = F/A; absolute vs. gauge pressure",
        "Hydrostatic pressure P = P₀ + ρgh and Pascal's principle (hydraulic lift)",
        "Buoyancy: Archimedes' principle, F_b = weight of displaced fluid; float vs. sink conditions",
        "Continuity equation A₁v₁ = A₂v₂ for incompressible flow",
        "Bernoulli's equation P + ρgy + ½ρv² = constant; Torricelli's law and lift",
      ],
      formulas: [
        "P = P₀ + ρgh",
        "F_b = ρ_fluid · V_sub · g",
        "A₁v₁ = A₂v₂ (continuity)",
        "P₁ + ρgy₁ + ½ρv₁² = P₂ + ρgy₂ + ½ρv₂²",
        "P_atm ≈ 1.01 × 10⁵ Pa",
      ],
      practice: [
        {
          id: "ph-fl-1", kind: "MC",
          prompt: "A wooden block (ρ = 600 kg/m³) floats in water (ρ = 1000 kg/m³). What fraction of its volume is submerged?",
          choices: ["A) 0.40", "B) 0.60", "C) 0.67", "D) 1.00"],
          answer: "B) 0.60",
          hint: "Floating means weight equals buoyant force: ρ_block·V = ρ_water·V_sub.",
          solution: "ρ_b·V·g = ρ_w·V_sub·g → V_sub/V = 600/1000 = 0.60.",
        },
        {
          id: "ph-fl-2", kind: "MC",
          prompt: "Water flows through a horizontal pipe that narrows from area A to A/2. How do the speed and pressure in the narrow section compare?",
          choices: ["A) speed doubles, pressure increases", "B) speed doubles, pressure decreases", "C) speed halves, pressure decreases", "D) speed doubles, pressure unchanged"],
          answer: "B) speed doubles, pressure decreases",
          hint: "Combine continuity (speed) with Bernoulli (pressure) for horizontal flow.",
          solution: "Continuity: v₂ = 2v₁. Bernoulli horizontal: higher v → lower P.",
        },
        {
          id: "ph-fl-3", kind: "MC",
          prompt: "A dam holds back water 12 m deep. The gauge pressure at the base is approximately:",
          choices: ["A) 1.2 × 10⁴ Pa", "B) 1.2 × 10⁵ Pa", "C) 2.2 × 10⁵ Pa", "D) 1.0 × 10⁵ Pa"],
          answer: "B) 1.2 × 10⁵ Pa",
          hint: "Gauge pressure excludes atmospheric: P = ρgh.",
          solution: "P = 1000 × 10 × 12 = 1.2 × 10⁵ Pa (using g ≈ 10).",
        },
        {
          id: "ph-fl-4", kind: "MC",
          prompt: "A hydraulic lift has pistons of area 0.05 m² and 2.0 m². A 200 N force on the small piston supports a maximum load of:",
          choices: ["A) 200 N", "B) 800 N", "C) 8000 N", "D) 80,000 N"],
          answer: "C) 8000 N",
          hint: "Pascal's principle: pressure transmits equally, F₂ = F₁(A₂/A₁).",
          solution: "F₂ = 200 × (2.0/0.05) = 200 × 40 = 8000 N.",
        },
        {
          id: "ph-fl-5", kind: "FRQ",
          prompt: "A large open tank drains through a small hole a depth h below the surface. (a) Derive the exit speed. (b) If the hole area doubles, what happens to the exit speed and the volume flow rate? Justify with Bernoulli and continuity.",
          answer: "(a) v = √(2gh); (b) speed unchanged, flow rate doubles",
          hint: "Apply Bernoulli between surface (v≈0) and hole; then Q = Av.",
          solution: "(a) P_atm + ρgh = P_atm + ½ρv² → v = √(2gh) (Torricelli). (b) v depends only on h, so unchanged; Q = A·v doubles with A.",
        },
        {
          id: "ph-fl-6", kind: "FRQ",
          prompt: "Design an experiment to determine the density of an unknown fluid using a spring scale, a metal block, and a beaker. List measurements, procedure, and how density is computed from a buoyant-force analysis.",
          answer: "ρ_fluid = (W_air − W_sub) / (V_block · g)",
          hint: "Apparent weight loss equals the buoyant force; you need the block's volume too.",
          solution: "Weigh block in air (W) and submerged (W′); F_b = W − W′ = ρ_f·V·g. Get V from mass/dimensions or known metal density, then ρ_f = (W − W′)/(Vg). Control: fully submerge without touching beaker.",
        },
      ],
    },
    {
      id: "thermo",
      title: "Thermodynamics & Kinetic Theory",
      weight: "10–12%",
      concepts: [
        "Ideal gas law PV = nRT = NkT; isothermal, isobaric, isochoric, adiabatic processes",
        "First law ΔU = Q + W (physics sign convention: work done ON the gas is positive)",
        "Kinetic theory: pressure from molecular collisions; rms speed; internal energy of ideal gas",
        "PV diagrams: work = area under curve; heat engines, efficiency e = W/Q_h = 1 − Q_c/Q_h",
        "Second law: entropy increases; heat flows hot → cold spontaneously",
      ],
      formulas: [
        "PV = nRT = Nk_B T",
        "ΔU = Q + W (W = work ON gas)",
        "W = −∫P dV (work BY gas = area under PV curve)",
        "K_avg = (3/2)k_B T per molecule",
        "e_max = 1 − T_c/T_h (Carnot)",
      ],
      practice: [
        {
          id: "ph-th-1", kind: "MC",
          prompt: "An ideal gas expands isothermally. Which is true?",
          choices: ["A) ΔU > 0 and Q = 0", "B) ΔU = 0 and Q = −W", "C) ΔU = 0 and W = 0", "D) Q = 0 and ΔU < 0"],
          answer: "B) ΔU = 0 and Q = −W",
          hint: "Isothermal → constant T → constant U for an ideal gas.",
          solution: "ΔU = 0, so 0 = Q + W → Q = −W. Gas does work (W<0), so heat enters (Q>0).",
        },
        {
          id: "ph-th-2", kind: "MC",
          prompt: "On a PV diagram, a gas goes from state A to B along two different paths. Which quantity is the SAME for both paths?",
          choices: ["A) Work done by the gas", "B) Heat added", "C) Change in internal energy", "D) None are the same"],
          answer: "C) Change in internal energy",
          hint: "Which thermodynamic quantities are state functions vs. path functions?",
          solution: "U is a state function — ΔU depends only on endpoints. Q and W are path-dependent.",
        },
        {
          id: "ph-th-3", kind: "MC",
          prompt: "The absolute temperature of an ideal gas doubles at constant volume. The average molecular kinetic energy:",
          choices: ["A) stays the same", "B) doubles", "C) quadruples", "D) increases by √2"],
          answer: "B) doubles",
          hint: "K_avg is directly proportional to T.",
          solution: "K_avg = (3/2)kT — doubling T doubles average KE.",
        },
        {
          id: "ph-th-4", kind: "MC",
          prompt: "A Carnot engine operates between 600 K and 300 K. Its maximum efficiency is:",
          choices: ["A) 25%", "B) 50%", "C) 67%", "D) 100%"],
          answer: "B) 50%",
          hint: "e = 1 − Tc/Th with Kelvin temperatures.",
          solution: "e = 1 − 300/600 = 0.50 = 50%.",
        },
        {
          id: "ph-th-5", kind: "FRQ",
          prompt: "One mole of ideal gas undergoes: A→B isobaric expansion doubling volume, B→C isochoric pressure drop back to P_A, C→A isothermal compression. (a) Sketch the PV diagram. (b) State the sign of Q, W (on gas), ΔU for each step. (c) Is net work positive or negative? Explain via enclosed area.",
          answer: "Net work done BY gas is positive (clockwise cycle); W_on negative",
          hint: "Clockwise PV cycle → net work done by the gas. Isotherm C→A: compression means work done on gas.",
          solution: "(a) A→B: rightward horizontal; B→C: downward vertical; C→A: curved isotherm up-left. (b) A→B: W<0, ΔU>0, Q>0. B→C: W=0, ΔU<0, Q<0. C→A: ΔU=0, W>0, Q<0. (c) Clockwise → area = net work BY gas > 0.",
        },
        {
          id: "ph-th-6", kind: "FRQ",
          prompt: "Explain, using kinetic theory, why a gas exerts pressure on container walls and why pressure rises when the gas is heated at constant volume. Reference molecular collisions and momentum transfer.",
          answer: "P from collision rate × momentum transfer; heating raises molecular speeds",
          hint: "Think about what happens at each wall collision and how temperature changes molecular motion.",
          solution: "Molecules collide elastically with walls, each transferring ~2mv of momentum; macroscopic pressure is the averaged force per area. Heating raises v_rms, so collisions are both harder (more Δp) and more frequent → higher P at fixed V.",
        },
      ],
    },
    {
      id: "em",
      title: "Electric Force, Field & Potential",
      weight: "12–14%",
      concepts: [
        "Coulomb's law F = kq₁q₂/r²; superposition and symmetry of charge distributions",
        "Electric field E = F/q; field lines; field of point charges and parallel plates (E = σ/ε₀)",
        "Electric potential V = U/q; equipotentials perpendicular to field lines",
        "Potential energy U = kq₁q₂/r; conservation of energy with charges",
        "Capacitors: C = Q/V; parallel-plate C = ε₀A/d; dielectrics increase C",
      ],
      formulas: [
        "F = k|q₁q₂|/r², k = 8.99 × 10⁹",
        "E_point = k|Q|/r²",
        "V_point = kQ/r; ΔV = −∫E·dl",
        "C_parallel = ε₀A/d",
        "U_cap = ½QV = ½CV² = Q²/2C",
      ],
      practice: [
        {
          id: "ph-em-1", kind: "MC",
          prompt: "Two point charges +Q and +4Q are fixed distance d apart. Where on the line between them is the net electric field zero?",
          choices: ["A) d/3 from +Q", "B) d/2 from +Q", "C) 2d/3 from +Q", "D) nowhere between them"],
          answer: "A) d/3 from +Q",
          hint: "Set kQ/x² = k(4Q)/(d−x)² and solve.",
          solution: "1/x² = 4/(d−x)² → (d−x) = 2x → x = d/3 from the smaller charge.",
        },
        {
          id: "ph-em-2", kind: "MC",
          prompt: "A proton is released from rest in a uniform field E pointing +x. Which is true of its motion?",
          choices: ["A) moves −x, KE decreases", "B) moves +x, KE increases", "C) moves +x, potential increases", "D) stays at rest"],
          answer: "B) moves +x, KE increases",
          hint: "Force on positive charge is along E; field does positive work.",
          solution: "F = qE accelerates it +x; KE rises as electric potential energy converts, moving toward lower V.",
        },
        {
          id: "ph-em-3", kind: "MC",
          prompt: "The separation of an isolated (disconnected) parallel-plate capacitor doubles. The voltage between plates:",
          choices: ["A) halves", "B) stays the same", "C) doubles", "D) quadruples"],
          answer: "C) doubles",
          hint: "Isolated → Q fixed; C halves when d doubles; V = Q/C.",
          solution: "C = ε₀A/d halves, so V = Q/C doubles.",
        },
        {
          id: "ph-em-4", kind: "MC",
          prompt: "Equipotential lines around a positive point charge are circles. The E-field direction is:",
          choices: ["A) tangent to the circles", "B) radially inward", "C) radially outward", "D) zero everywhere"],
          answer: "C) radially outward",
          hint: "Field is always perpendicular to equipotentials, pointing from high to low V.",
          solution: "V = kQ/r is higher near the charge; E points down the steepest descent — radially outward.",
        },
        {
          id: "ph-em-5", kind: "FRQ",
          prompt: "An electron (q = −e, m) accelerates from rest through 500 V, then enters a uniform field region. (a) Find its speed after acceleration. (b) Explain how you would arrange parallel plates to deflect it vertically, with diagram and force reasoning.",
          answer: "(a) v = √(2eV/m) ≈ 1.3 × 10⁷ m/s",
          hint: "Energy conservation: eV = ½mv².",
          solution: "(a) ½mv² = e(500) → v = √(2·1.6e-19·500/9.11e-31) ≈ 1.33×10⁷ m/s. (b) Place horizontal plates (E vertical); the negative electron deflects opposite E, toward the positive plate; F = eE gives parabolic trajectory.",
        },
        {
          id: "ph-em-6", kind: "FRQ",
          prompt: "Two identical conducting spheres: A has +6 μC, B is neutral. They touch, then separate to 0.30 m. (a) What is each sphere's charge? (b) Find the force magnitude and state attraction/repulsion. (c) Explain the charge-sharing microscopically.",
          answer: "(a) +3 μC each; (b) ≈ 0.9 N repulsion",
          hint: "Touching identical conductors splits net charge evenly.",
          solution: "(a) Total +6 μC → +3 μC each. (b) F = k(3e-6)²/0.09 ≈ 0.9 N, repulsive (like charges). (c) Mobile electrons redistribute until both spheres are equipotentials; symmetry of identical spheres gives equal sharing.",
        },
      ],
    },
    {
      id: "circuits",
      title: "DC & RC Circuits",
      weight: "10–12%",
      concepts: [
        "Current I = ΔQ/Δt; resistance R = ρL/A; Ohm's law V = IR",
        "Series vs. parallel: combining resistors; voltage/current division",
        "Kirchhoff's rules: junction (charge conservation) and loop (energy conservation)",
        "Power P = IV = I²R = V²/R; batteries, emf, internal resistance",
        "RC circuits: charging/discharging curves, time constant τ = RC",
      ],
      formulas: [
        "V = IR; R = ρL/A",
        "Series: R_eq = ΣR; Parallel: 1/R_eq = Σ(1/R)",
        "P = IV = I²R = V²/R",
        "Q(t) = Q_max(1 − e^(−t/RC)) charging",
        "τ = RC",
      ],
      practice: [
        {
          id: "ph-ci-1", kind: "MC",
          prompt: "Resistors 2 Ω and 3 Ω in parallel connect to a 12 V battery. Total current from the battery is:",
          choices: ["A) 2.4 A", "B) 5.0 A", "C) 10 A", "D) 12 A"],
          answer: "C) 10 A",
          hint: "R_eq = (2·3)/(2+3); then I = V/R.",
          solution: "R_eq = 1.2 Ω; I = 12/1.2 = 10 A.",
        },
        {
          id: "ph-ci-2", kind: "MC",
          prompt: "A wire's length doubles and diameter halves. Its resistance changes by factor:",
          choices: ["A) 2", "B) 4", "C) 8", "D) 16"],
          answer: "C) 8",
          hint: "R = ρL/A; halving diameter quarters the area.",
          solution: "L→2L (×2), A→A/4 (×4) → R ×8.",
        },
        {
          id: "ph-ci-3", kind: "MC",
          prompt: "In an RC charging circuit, after one time constant (t = τ) the capacitor holds what fraction of max charge?",
          choices: ["A) 37%", "B) 50%", "C) 63%", "D) 95%"],
          answer: "C) 63%",
          hint: "Q = Qmax(1 − e^(−t/τ)); e^(−1) ≈ 0.37.",
          solution: "1 − 1/e ≈ 0.63.",
        },
        {
          id: "ph-ci-4", kind: "MC",
          prompt: "Two identical bulbs in series with a battery vs. in parallel (same battery). The parallel pair is:",
          choices: ["A) dimmer, same total power", "B) brighter, more total power", "C) same brightness", "D) brighter, same total power"],
          answer: "B) brighter, more total power",
          hint: "Compare voltage across each bulb: V/2 (series) vs. full V (parallel).",
          solution: "Parallel bulbs each see full V → P = V²/R each, brighter; total 2V²/R vs. series total V²/2R.",
        },
        {
          id: "ph-ci-5", kind: "FRQ",
          prompt: "A 6 V battery (negligible internal resistance) connects to 2 Ω and 4 Ω resistors in series. (a) Find the current and voltage across each resistor. (b) Compute power dissipated in each. (c) If a wire shorts across the 4 Ω resistor, describe and justify the new current.",
          answer: "(a) I = 1 A; V₂ = 2 V, V₄ = 4 V; (b) 2 W, 4 W; (c) I = 3 A",
          hint: "Series: same current, voltages divide by resistance.",
          solution: "(a) R = 6 Ω → I = 1 A; V = IR gives 2 V and 4 V. (b) P = I²R: 2 W, 4 W. (c) Shorted 4 Ω carries no current; R = 2 Ω → I = 3 A, all 6 V across the 2 Ω resistor.",
        },
        {
          id: "ph-ci-6", kind: "FRQ",
          prompt: "For a discharging RC circuit, (a) derive I(t) from Q(t) = Q₀e^(−t/RC), and (b) describe an experiment using a voltage sensor to verify τ = RC, including what you would plot to get a straight line.",
          answer: "(a) I = (Q₀/RC)e^(−t/RC); (b) plot ln V vs. t, slope = −1/RC",
          hint: "Current is the rate of charge loss; linearize the exponential with a log plot.",
          solution: "(a) I = −dQ/dt = (Q₀/RC)e^(−t/RC). (b) Record V(t); since V = V₀e^(−t/RC), plot ln(V) vs. t → straight line with slope −1/(RC); compare fitted τ to component values.",
        },
      ],
    },
    {
      id: "magnetism",
      title: "Magnetism & EM Induction",
      weight: "10–12%",
      concepts: [
        "Magnetic force on moving charge F = qvB sinθ; right-hand rule; circular motion r = mv/qB",
        "Force on current-carrying wire F = BIL sinθ; torque on loops (motors)",
        "Fields of long wires (B = μ₀I/2πr), loops, solenoids (B = μ₀nI)",
        "Faraday's law ε = −NΔΦ/Δt; magnetic flux Φ = BA cosθ",
        "Lenz's law: induced current opposes the flux change; motional emf ε = BLv",
      ],
      formulas: [
        "F = |q|vB sinθ; r = mv/(qB)",
        "B_wire = μ₀I/(2πr); B_sol = μ₀nI",
        "Φ_B = BA cosθ",
        "ε = −N ΔΦ/Δt",
        "ε_motional = BLv",
      ],
      practice: [
        {
          id: "ph-ma-1", kind: "MC",
          prompt: "A proton moves +x through B pointing +z. The magnetic force direction is:",
          choices: ["A) +y", "B) −y", "C) +x", "D) −z"],
          answer: "B) −y",
          hint: "Right-hand rule: v × B for a positive charge. x̂ × ẑ = −ŷ.",
          solution: "F = q(v × B); x̂ × ẑ = −ŷ, so force is −y.",
        },
        {
          id: "ph-ma-2", kind: "MC",
          prompt: "A bar magnet's north pole moves toward a loop. The induced current, viewed from the magnet side:",
          choices: ["A) clockwise, attracting the magnet", "B) counterclockwise, repelling the magnet", "C) clockwise, repelling the magnet", "D) zero"],
          answer: "B) counterclockwise, repelling the magnet",
          hint: "Lenz's law: the loop fights the increasing toward-flux by making its own facing field.",
          solution: "Induced field must point back toward the magnet (repel) → counterclockwise viewed from magnet side.",
        },
        {
          id: "ph-ma-3", kind: "MC",
          prompt: "Doubling both the speed and field for a charge in circular magnetic motion changes the radius by factor:",
          choices: ["A) 1 (unchanged)", "B) 2", "C) 4", "D) 1/2"],
          answer: "A) 1 (unchanged)",
          hint: "r = mv/qB.",
          solution: "r ∝ v/B; both double → ratio unchanged.",
        },
        {
          id: "ph-ma-4", kind: "MC",
          prompt: "A solenoid's current doubles and its turn density triples. Its interior field changes by factor:",
          choices: ["A) 5", "B) 6", "C) 9", "D) 12"],
          answer: "B) 6",
          hint: "B = μ₀nI — linear in both n and I.",
          solution: "2 × 3 = 6.",
        },
        {
          id: "ph-ma-5", kind: "FRQ",
          prompt: "A 0.20 m rod slides at 3.0 m/s on rails through B = 0.50 T (into page). Rails connect to a 4.0 Ω resistor. (a) Find motional emf and current direction. (b) Find the magnetic force on the rod and the mechanical power needed to keep it moving at constant speed.",
          answer: "(a) 0.30 V; (b) 0.011 N, 0.034 W",
          hint: "ε = BLv; power in = power dissipated in resistor.",
          solution: "(a) ε = 0.5×0.2×3 = 0.30 V; I = 0.075 A, Lenz direction opposing motion. (b) F = BIL ≈ 0.011 N opposing motion; P = Fv ≈ 0.034 W (= I²R).",
        },
        {
          id: "ph-ma-6", kind: "FRQ",
          prompt: "A loop of area 0.010 m² with 50 turns sits in a field that drops from 0.40 T to 0 in 0.20 s, field perpendicular to the loop. (a) Compute average induced emf. (b) If the loop's plane were parallel to the field instead, what emf? Justify with flux.",
          answer: "(a) 1.0 V; (b) 0",
          hint: "ε = N·A·ΔB/Δt for perpendicular orientation.",
          solution: "(a) ε = 50×0.010×0.40/0.20 = 1.0 V. (b) cos90° = 0 → no flux, no change, ε = 0.",
        },
      ],
    },
    {
      id: "optics",
      title: "Geometric & Physical Optics",
      weight: "10–12%",
      concepts: [
        "Reflection (θᵢ = θᵣ) and refraction: Snell's law n₁sinθ₁ = n₂sinθ₂",
        "Total internal reflection and critical angle sinθc = n₂/n₁",
        "Mirrors/lenses: thin-lens equation 1/f = 1/dₒ + 1/dᵢ; magnification M = −dᵢ/dₒ",
        "Real vs. virtual images; ray diagrams for concave/convex mirrors and lenses",
        "Wave optics: double-slit interference, diffraction; Polarization (Malus's law)",
      ],
      formulas: [
        "n₁ sinθ₁ = n₂ sinθ₂",
        "sinθc = n₂/n₁ (n₁ > n₂)",
        "1/f = 1/dₒ + 1/dᵢ; M = −dᵢ/dₒ = hᵢ/hₒ",
        "d sinθ = mλ (bright fringes)",
        "I = I₀ cos²θ (Malus)",
      ],
      practice: [
        {
          id: "ph-op-1", kind: "MC",
          prompt: "Light goes from glass (n = 1.5) to air. The critical angle is closest to:",
          choices: ["A) 28°", "B) 42°", "C) 48°", "D) 62°"],
          answer: "B) 42°",
          hint: "sinθc = 1/1.5.",
          solution: "sinθc = 0.667 → θc ≈ 41.8°.",
        },
        {
          id: "ph-op-2", kind: "MC",
          prompt: "An object stands outside 2F of a converging lens. The image is:",
          choices: ["A) virtual, upright, enlarged", "B) real, inverted, reduced", "C) real, upright, same size", "D) no image forms"],
          answer: "B) real, inverted, reduced",
          hint: "Far object through converging lens: image between F and 2F on the far side.",
          solution: "Standard ray diagram gives a real inverted diminished image.",
        },
        {
          id: "ph-op-3", kind: "MC",
          prompt: "In a double-slit experiment, the wavelength doubles while everything else stays fixed. Fringe spacing:",
          choices: ["A) halves", "B) stays the same", "C) doubles", "D) quadruples"],
          answer: "C) doubles",
          hint: "Fringe spacing Δy = λL/d.",
          solution: "Spacing is directly proportional to λ.",
        },
        {
          id: "ph-op-4", kind: "MC",
          prompt: "Unpolarized light of intensity I₀ passes through two polarizers with axes 60° apart. Transmitted intensity is:",
          choices: ["A) 0.125 I₀", "B) 0.25 I₀", "C) 0.375 I₀", "D) 0.5 I₀"],
          answer: "A) 0.125 I₀",
          hint: "First polarizer halves; Malus's law for the second.",
          solution: "I₁ = I₀/2; I₂ = I₁cos²60° = (I₀/2)(0.25) = 0.125I₀.",
        },
        {
          id: "ph-op-5", kind: "FRQ",
          prompt: "An object 3.0 cm tall sits 12 cm from a converging lens of f = 4.0 cm. (a) Locate and characterize the image. (b) Draw the three principal rays to justify your answer.",
          answer: "dᵢ = 6.0 cm, real, inverted, 1.5 cm tall",
          hint: "1/12 + 1/dᵢ = 1/4.",
          solution: "(a) 1/dᵢ = 1/4 − 1/12 = 1/6 → dᵢ = 6 cm (real side); M = −6/12 = −0.5 → inverted, 1.5 cm. (b) Parallel→F ray, central ray straight, F→parallel ray all meet at image.",
        },
        {
          id: "ph-op-6", kind: "FRQ",
          prompt: "Explain why a double-slit pattern shows equally spaced bright fringes but a single-slit pattern shows a broad central maximum. Include the relevant path-difference reasoning.",
          answer: "Two-source interference vs. extended-source cancellation",
          hint: "Compare d sinθ = mλ with the single-slit condition a sinθ = mλ for minima.",
          solution: "Double-slit: two coherent sources interfere constructively when path difference is mλ at every order → evenly spaced fringes. Single slit: light from across one wide opening cancels pairwise at a sinθ = mλ, suppressing all but a broad central lobe twice as wide as the rest.",
        },
      ],
    },
    {
      id: "modern",
      title: "Modern Physics: Quantum, Atomic & Nuclear",
      weight: "8–10%",
      concepts: [
        "Photoelectric effect: K_max = hf − φ; threshold frequency; photons E = hf",
        "Wave-particle duality; de Broglie wavelength λ = h/p",
        "Atomic models: Bohr energy levels E_n = −13.6 eV/n²; emission/absorption spectra",
        "Nuclear structure, binding energy (E = mc²), fission vs. fusion",
        "Radioactive decay: half-life; conservation of nucleon number and charge",
      ],
      formulas: [
        "E_photon = hf = hc/λ",
        "K_max = hf − φ",
        "λ = h/p (de Broglie)",
        "E_n = −13.6 eV/n² (hydrogen)",
        "E = mc²; 1 u ≈ 931.5 MeV",
      ],
      practice: [
        {
          id: "ph-mo-1", kind: "MC",
          prompt: "Light of frequency f ejects electrons with K_max = 2.0 eV from a metal with work function 3.0 eV. Doubling the light intensity (same f):",
          choices: ["A) K_max doubles", "B) K_max stays 2.0 eV, more electrons", "C) no electrons emitted", "D) K_max halves"],
          answer: "B) K_max stays 2.0 eV, more electrons",
          hint: "Intensity changes photon count, not photon energy.",
          solution: "K_max = hf − φ depends only on f; more photons → more electrons at the same energy.",
        },
        {
          id: "ph-mo-2", kind: "MC",
          prompt: "An electron and proton have the same kinetic energy. Which has the longer de Broglie wavelength?",
          choices: ["A) proton", "B) electron", "C) equal", "D) neither has wavelength"],
          answer: "B) electron",
          hint: "λ = h/p; at fixed KE, p = √(2mK) — lighter mass means less momentum.",
          solution: "Electron's smaller mass gives smaller p and hence larger λ.",
        },
        {
          id: "ph-mo-3", kind: "MC",
          prompt: "A hydrogen electron drops from n = 3 to n = 2. The emitted photon energy is:",
          choices: ["A) 1.89 eV", "B) 3.40 eV", "C) 10.2 eV", "D) 13.6 eV"],
          answer: "A) 1.89 eV",
          hint: "ΔE = 13.6(1/4 − 1/9).",
          solution: "13.6 × (0.25 − 0.111) = 13.6 × 0.139 ≈ 1.89 eV (H-alpha red line).",
        },
        {
          id: "ph-mo-4", kind: "MC",
          prompt: "A sample's activity drops to 1/8 of initial. How many half-lives elapsed?",
          choices: ["A) 2", "B) 3", "C) 4", "D) 8"],
          answer: "B) 3",
          hint: "(1/2)^n = 1/8.",
          solution: "n = 3.",
        },
        {
          id: "ph-mo-5", kind: "FRQ",
          prompt: "In a photoelectric experiment, 400 nm light produces electrons with K_max = 1.1 eV. (a) Compute the photon energy in eV. (b) Find the work function. (c) Predict what happens to K_max and photocurrent if wavelength switches to 300 nm at the same intensity.",
          answer: "(a) ≈ 3.1 eV; (b) ≈ 2.0 eV; (c) K_max rises, current falls",
          hint: "E = hc/λ with hc ≈ 1240 eV·nm.",
          solution: "(a) E = 1240/400 = 3.1 eV. (b) φ = 3.1 − 1.1 = 2.0 eV. (c) 300 nm → 4.13 eV photons → K_max ≈ 2.1 eV; fewer photons at fixed intensity → lower current.",
        },
        {
          id: "ph-mo-6", kind: "FRQ",
          prompt: "Explain how mass-energy equivalence accounts for the energy released in nuclear fission, referencing binding energy per nucleon and why the products' total mass is less than the parent's.",
          answer: "Missing mass becomes kinetic energy via E = mc²; products more tightly bound",
          hint: "Consider the binding-energy-per-nucleon curve and where heavy nuclei sit on it.",
          solution: "Heavy nuclei have lower binding energy per nucleon than mid-mass fragments; splitting into more tightly bound products increases total binding energy, and the difference appears as the mass deficit Δm released as KE/radiation via E = Δmc².",
        },
      ],
    },
  ],
};
