import type { Subject } from "./types";

export const stats: Subject = {
  id: "stats",
  name: "AP Statistics",
  short: "Stats",
  tagline: "Data exploration, sampling, probability & inference",
  color: "#059669",
  soft: "#d1fae5",
  exam: {
    format: "3 hrs · 40 MCQ (50%) + 6 FRQ (50%)",
    mcq: "40 multiple-choice, 90 min — including paired data-analysis stems",
    frq: "6 free-response: 5 short (4 pts) + 1 investigative task (6 pts); clear communication is graded",
  },
  tips: [
    "Always name the procedure AND check conditions (Random, Independent/10%, Normal/Large counts) — no conditions, no credit.",
    "Interpretation sentences need three parts: direction/magnitude, context with units, and the confidence or significance level.",
    "On FRQs, show the formula with numbers plugged in before the calculator result — setup earns partial credit.",
    "Distinguish standard deviation (spread of data) from standard error (spread of a sampling distribution).",
    "For the investigative task, think: graph first, then split by a variable, then quantify — graders reward the full cycle.",
  ],
  units: [
    {
      id: "exploring-1var",
      title: "Exploring One-Variable Data",
      weight: "8–12%",
      concepts: [
        "Graphical displays: dotplots, stemplots, histograms, boxplots; shape, center, spread, outliers (SOCS)",
        "Median, mean, quartiles, IQR; 1.5×IQR outlier rule",
        "Standard deviation and variance as measures of spread around the mean",
        "Comparing distributions with parallel plots in context",
        "Normal model: empirical rule, z-scores, percentiles",
      ],
      formulas: [
        "z = (x − μ)/σ",
        "IQR = Q3 − Q1; outlier if beyond Q ± 1.5×IQR",
        "Empirical rule: 68-95-99.7 within 1-2-3 SD",
        "s = √[Σ(x − x̄)²/(n−1)]",
      ],
      practice: [
        {
          id: "st-1v-1", kind: "MC",
          prompt: "A right-skewed distribution of incomes has mean $72k and median $58k. Adding a $5M outlier will:",
          choices: ["A) raise median more than mean", "B) raise mean more than median", "C) lower both equally", "D) change neither"],
          answer: "B) raise mean more than median",
          hint: "Which measure resists outliers?",
          solution: "The mean uses every value so it shifts strongly; the median barely moves.",
        },
        {
          id: "st-1v-2", kind: "MC",
          prompt: "Test scores are approximately Normal with μ = 75, σ = 8. About what percent score above 91?",
          choices: ["A) 2.5%", "B) 5%", "C) 16%", "D) 32%"],
          answer: "A) 2.5%",
          hint: "91 is 2 SD above the mean; combine the empirical rule tails.",
          solution: "Above μ+2σ ≈ (100 − 95)/2 = 2.5%.",
        },
        {
          id: "st-1v-3", kind: "MC",
          prompt: "Q1 = 20, Q3 = 40. Which value is an outlier by the 1.5×IQR rule?",
          choices: ["A) 0", "B) 58", "C) 62", "D) 78"],
          answer: "D) 78",
          hint: "IQR = 20; fences at 20−30 and 40+30.",
          solution: "IQR = 20 → 1.5×IQR = 30. Fences: −10 and 70. Only 78 exceeds the upper fence.",
        },
        {
          id: "st-1v-4", kind: "MC",
          prompt: "Which display is best for checking whether a distribution is approximately Normal?",
          choices: ["A) pie chart", "B) segmented bar graph", "C) normal probability plot", "D) scatterplot"],
          answer: "C) normal probability plot",
          hint: "Linear pattern in a specific diagnostic plot signals normality.",
          solution: "A roughly straight normal quantile plot supports normality.",
        },
        {
          id: "st-1v-5", kind: "FRQ",
          prompt: "Back-to-back stemplots show quiz scores for Period A (skewed right, median 82) and Period B (symmetric, mean ≈ median ≈ 79). (a) Compare shape, center, spread. (b) Which class likely has the larger SD? Justify.",
          answer: "A: higher center, right skew; B larger or smaller spread depends on range — justify from plot",
          hint: "Use SOCS in context and link skew to mean-vs-median pull.",
          solution: "(a) Shape: A right-skewed vs. B symmetric. Center: A median 82 > B 79. Spread: compare ranges/IQRs from the plot in points. (b) The class with the wider range / longer tails has larger SD since SD averages squared deviations.",
        },
        {
          id: "st-1v-6", kind: "FRQ",
          prompt: "Heights are Normal(μ = 170 cm, σ = 8 cm). (a) Find P(X > 182). (b) Find the 90th percentile. Show z-score work.",
          answer: "(a) ≈ 0.067; (b) ≈ 180.3 cm",
          hint: "z = 1.5 for part (a); z* = 1.28 for the 90th percentile.",
          solution: "(a) z = (182−170)/8 = 1.5 → tail ≈ 0.0668. (b) x = 170 + 1.28(8) ≈ 180.2 cm.",
        },
      ],
    },
    {
      id: "exploring-2var",
      title: "Exploring Two-Variable Data",
      weight: "6–10%",
      concepts: [
        "Scatterplots: direction, form, strength, unusual points",
        "Correlation r: −1 to 1, measures linear strength; not resistant, no causation",
        "Least-squares regression line: ŷ = a + bx; interpreting slope and y-intercept",
        "Residuals, residual plots, s (residual SD) and R² (variance explained)",
        "Transforming to linearity (log/power); influential points vs. outliers",
      ],
      formulas: [
        "b = r(s_y/s_x); a = ȳ − bx̄",
        "residual = observed − predicted",
        "R² = fraction of variation in y explained by x",
        "r ∈ [−1, 1]",
      ],
      practice: [
        {
          id: "st-2v-1", kind: "MC",
          prompt: "A scatterplot shows a strong curved pattern with r = 0.15. The best conclusion is:",
          choices: ["A) weak relationship", "B) strong nonlinear relationship; r is misleading", "C) no relationship", "D) causation proven"],
          answer: "B) strong nonlinear relationship; r is misleading",
          hint: "r only measures linear association.",
          solution: "A curve can be strong yet give r ≈ 0; check the plot, not just r.",
        },
        {
          id: "st-2v-2", kind: "MC",
          prompt: "Regression of test score on study hours: ŷ = 55 + 4.2x. Correct slope interpretation:",
          choices: ["A) each extra hour causes +4.2 points", "B) predicted score rises 4.2 points per extra hour", "C) correlation is 4.2", "D) intercept is meaningless so model is invalid"],
          answer: "B) predicted score rises 4.2 points per extra hour",
          hint: "Avoid causal language in observational interpretations.",
          solution: "Slope = predicted change in y per unit x.",
        },
        {
          id: "st-2v-3", kind: "MC",
          prompt: "R² = 0.81. The correct interpretation is:",
          choices: ["A) 81% of data fall on the line", "B) 81% of variation in y is explained by the linear model", "C) correlation is 0.81", "D) slope is 0.81"],
          answer: "B) 81% of variation in y is explained by the linear model",
          hint: "R² is about variance explained, and r = ±√R².",
          solution: "R² = 0.81 → r = ±0.9; interpretation concerns explained variation.",
        },
        {
          id: "st-2v-4", kind: "MC",
          prompt: "A residual plot shows a clear U-shape. This indicates:",
          choices: ["A) perfect linear fit", "B) non-constant spread only", "C) nonlinearity — consider a transformation", "D) an outlier"],
          answer: "C) nonlinearity — consider a transformation",
          hint: "Good linear fits leave patternless residuals.",
          solution: "Curved residuals mean the linear model is systematically wrong; try log/power transforms.",
        },
        {
          id: "st-2v-5", kind: "FRQ",
          prompt: "Data on car age (x) vs. price (y): ŷ = 24,000 − 1,800x, r = −0.92, s = $1,200. (a) Interpret slope, intercept, R², s in context. (b) A 2-year-old car costs $25,000. Compute its residual and say whether the model under- or over-predicted.",
          answer: "(b) residual = +$4,600 (under-predicted)",
          hint: "Predicted = 24,000 − 1,800(2).",
          solution: "(a) Slope: predicted price falls $1,800 per year of age. Intercept: predicted price of a new car $24,000. R² = 0.846: ~85% of price variation explained. s: typical prediction error ~$1,200. (b) Predicted $20,400; residual = 25,000 − 20,400 = +$4,600 → model under-predicted.",
        },
        {
          id: "st-2v-6", kind: "FRQ",
          prompt: "Explain the difference between an outlier and an influential point in regression, and describe how each appears on a scatterplot vs. a residual plot.",
          answer: "Outlier: large residual; influential: changes the line",
          hint: "Think y-direction weirdness vs. x-direction leverage combined with weirdness.",
          solution: "An outlier has a large residual (far from the pattern in y). An influential point substantially changes slope/intercept — typically high-leverage x plus off-pattern y. Outliers stand out on residual plots; influential points are spotted by refitting without them.",
        },
      ],
    },
    {
      id: "collecting-data",
      title: "Collecting Data: Sampling & Experiments",
      weight: "8–12%",
      concepts: [
        "Population vs. sample; census, simple random, stratified, cluster, systematic samples",
        "Bias: undercoverage, nonresponse, voluntary response, leading questions",
        "Experiments: explanatory/response variables, treatments, control, randomization, blinding",
        "Completely randomized, randomized block, matched pairs designs",
        "Scope of inference: random sampling → generalization; random assignment → causation",
      ],
      formulas: [
        "No computation formulas — vocabulary + design logic unit",
        "Random sampling ⇒ generalize to population",
        "Random assignment ⇒ cause-and-effect conclusion",
      ],
      practice: [
        {
          id: "st-cd-1", kind: "MC",
          prompt: "A pollster surveys only customers who call a hotline to complain. This suffers from:",
          choices: ["A) undercoverage only", "B) voluntary response bias", "C) confounding", "D) placebo effect"],
          answer: "B) voluntary response bias",
          hint: "Who chooses to be in the sample?",
          solution: "Self-selected respondents with strong opinions overrepresent extremes.",
        },
        {
          id: "st-cd-2", kind: "MC",
          prompt: "To compare two fertilizers while accounting for field fertility gradients, the best design is:",
          choices: ["A) convenience sample", "B) randomized block design", "C) voluntary response", "D) census"],
          answer: "B) randomized block design",
          hint: "Group similar plots first, then randomize within groups.",
          solution: "Blocking on fertility removes that variation from the comparison.",
        },
        {
          id: "st-cd-3", kind: "MC",
          prompt: "A study randomly assigns diabetics to a new drug or placebo, double-blind. A significant improvement in the drug group supports:",
          choices: ["A) correlation only", "B) causation, generalizable to all people", "C) causation for similar patients", "D) nothing without a census"],
          answer: "C) causation for similar patients",
          hint: "Random assignment gives causation; generalization needs random sampling.",
          solution: "Assignment → cause; but volunteers aren't a random sample of everyone.",
        },
        {
          id: "st-cd-4", kind: "MC",
          prompt: "Stratified sampling of 50 freshmen, 50 sophomores, 50 juniors, 50 seniors is used instead of SRS because it:",
          choices: ["A) removes all bias", "B) guarantees representation of each class", "C) allows causation", "D) is a census"],
          answer: "B) guarantees representation of each class",
          hint: "Strata ensure small subgroups appear in the sample.",
          solution: "SRS might randomly miss a class; stratification fixes the composition.",
        },
        {
          id: "st-cd-5", kind: "FRQ",
          prompt: "A principal wants to know if later start times improve test scores. (a) Design a randomized experiment using two homerooms. (b) Identify explanatory/response variables, treatments, and how you control confounding. (c) Can results generalize to all US schools? Explain.",
          answer: "Randomly assign start times; scores are response",
          hint: "Random assignment of the two times, not student choice.",
          solution: "(a) Randomly assign one homeroom to early, one to late start (or randomize students); keep curriculum/teacher constant; blind grading. (b) Explanatory: start time; response: scores; treatments: early vs. late; control via same tests, pacing. (c) No — one school is not a random sample of schools; inference limited to similar students.",
        },
        {
          id: "st-cd-6", kind: "FRQ",
          prompt: "Explain confounding with a concrete example: a study finds coffee drinkers have higher heart-attack rates. Identify a likely confounding variable and describe a design that would address it.",
          answer: "Smoking correlates with coffee and causes heart attacks",
          hint: "Find a third variable linked to both exposure and outcome.",
          solution: "Smoking is a confounder: associated with heavy coffee use and causally raises heart risk. A randomized trial of coffee (or a well-controlled observational analysis stratifying/adjusting for smoking) separates the effects.",
        },
      ],
    },
    {
      id: "probability",
      title: "Probability & Random Variables",
      weight: "10–14%",
      concepts: [
        "Probability rules: addition, multiplication, complement, conditional P(A|B)",
        "Independence vs. disjointness; two-way tables, Venn diagrams, tree diagrams",
        "Discrete random variables: mean and variance; linear transformations",
        "Binomial (B(n,p)) and geometric distributions: conditions, mean, SD",
        "Combining independent random variables: means add; variances add (not SDs)",
      ],
      formulas: [
        "P(A|B) = P(A∩B)/P(B)",
        "μ_X = Σx·P(x); σ²_X = Σ(x−μ)²P(x)",
        "Binomial: μ = np, σ = √(np(1−p))",
        "Geometric: μ = 1/p",
        "For independent X,Y: μ_{X±Y} = μ_X ± μ_Y; σ²_{X±Y} = σ²_X + σ²_Y",
      ],
      practice: [
        {
          id: "st-pr-1", kind: "MC",
          prompt: "P(A) = 0.4, P(B) = 0.5, P(A∩B) = 0.2. P(A|B) equals:",
          choices: ["A) 0.2", "B) 0.4", "C) 0.5", "D) 0.9"],
          answer: "B) 0.4",
          hint: "Divide the joint probability by P(B).",
          solution: "0.2/0.5 = 0.4 (here A and B are independent).",
        },
        {
          id: "st-pr-2", kind: "MC",
          prompt: "Free throws hit at 80%. Probability of making exactly 4 of 5 (order irrelevant) is:",
          choices: ["A) (0.8)⁴(0.2)", "B) 5(0.8)⁴(0.2)", "C) (0.8)⁵", "D) 1 − (0.2)⁵"],
          answer: "B) 5(0.8)⁴(0.2)",
          hint: "Binomial with n = 5, k = 4.",
          solution: "C(5,4)(0.8)⁴(0.2) = 5(0.8)⁴(0.2).",
        },
        {
          id: "st-pr-3", kind: "MC",
          prompt: "X has μ = 10, σ = 2. For Y = 3X + 5, the mean and SD are:",
          choices: ["A) 35 and 6", "B) 35 and 11", "C) 30 and 6", "D) 15 and 2"],
          answer: "A) 35 and 6",
          hint: "Mean shifts and scales; SD scales by |3| only (the +5 adds nothing).",
          solution: "μ_Y = 3(10)+5 = 35; σ_Y = 3(2) = 6. Answer A.",
        },
        {
          id: "st-pr-4", kind: "MC",
          prompt: "Independent X (μ=4, σ=1) and Y (μ=7, σ=2). The SD of X + Y is:",
          choices: ["A) 3", "B) √5 ≈ 2.24", "C) 5", "D) 1.5"],
          answer: "B) √5 ≈ 2.24",
          hint: "Add variances, then square-root.",
          solution: "σ² = 1 + 4 = 5 → σ = √5.",
        },
        {
          id: "st-pr-5", kind: "FRQ",
          prompt: "A bag has 3 red and 7 blue marbles. Two drawn without replacement. (a) P(both red)? (b) P(at least one red)? Use conditional probability reasoning and check with a tree or table.",
          answer: "(a) ≈ 0.067; (b) ≈ 0.533",
          hint: "Without replacement, denominators change: (3/10)(2/9).",
          solution: "(a) (3/10)(2/9) = 6/90 ≈ 0.067. (b) 1 − P(both blue) = 1 − (7/10)(6/9) = 1 − 0.467 = 0.533.",
        },
        {
          id: "st-pr-6", kind: "FRQ",
          prompt: "Emergency calls arrive with 25% requiring overtime. For 12 calls: (a) verify binomial conditions, (b) find P(exactly 3 overtime), (c) mean and SD of overtime count.",
          answer: "(b) ≈ 0.258; (c) μ = 3, σ = 1.5",
          hint: "BINS: Binary, Independent, Number fixed, Same p.",
          solution: "(a) Binary outcome, independent calls, n = 12 fixed, p = 0.25 constant — binomial OK. (b) C(12,3)(0.25)³(0.75)⁹ ≈ 0.258. (c) μ = 3, σ = √(12·0.25·0.75) = 1.5.",
        },
      ],
    },
    {
      id: "sampling-dist",
      title: "Sampling Distributions",
      weight: "8–12%",
      concepts: [
        "Sampling distribution of x̄ and p̂: center, spread, shape",
        "Central Limit Theorem: x̄ ≈ Normal for large n regardless of population shape",
        "Standard errors: σ/√n and √(p(1−p)/n)",
        "Conditions: Random, 10% (independence), Large Counts / n ≥ 30",
        "Simulations to approximate sampling distributions",
      ],
      formulas: [
        "μ_x̄ = μ; σ_x̄ = σ/√n",
        "μ_p̂ = p; σ_p̂ = √(p(1−p)/n)",
        "CLT: n ≥ 30 (or Normal population) → x̄ approx Normal",
        "Large counts: np ≥ 10 and n(1−p) ≥ 10",
      ],
      practice: [
        {
          id: "st-sd-1", kind: "MC",
          prompt: "Population skewed right, μ = 50, σ = 12, n = 64. The sampling distribution of x̄ is approximately:",
          choices: ["A) skewed right, mean 50, SE 12", "B) Normal, mean 50, SE 1.5", "C) Normal, mean 50, SE 12", "D) bimodal"],
          answer: "B) Normal, mean 50, SE 1.5",
          hint: "CLT with n = 64; SE = σ/√n.",
          solution: "12/√64 = 1.5; shape ≈ Normal by CLT.",
        },
        {
          id: "st-sd-2", kind: "MC",
          prompt: " quadrupling sample size changes the standard error by factor:",
          choices: ["A) 1/4", "B) 1/2", "C) 2", "D) unchanged"],
          answer: "B) 1/2",
          hint: "SE ∝ 1/√n.",
          solution: "√4 = 2 → SE halves.",
        },
        {
          id: "st-sd-3", kind: "MC",
          prompt: "For p̂ with p = 0.3, n = 100, the sampling distribution has mean and SD:",
          choices: ["A) 0.3 and 0.046", "B) 30 and 4.6", "C) 0.3 and 0.21", "D) 0.5 and 0.05"],
          answer: "A) 0.3 and 0.046",
          hint: "σ_p̂ = √(0.3·0.7/100).",
          solution: "√(0.0021) ≈ 0.0458.",
        },
        {
          id: "st-sd-4", kind: "MC",
          prompt: "Which condition lets us use a Normal model for p̂ when n = 40, p = 0.2?",
          choices: ["A) np = 8 < 10, so not met", "B) n ≥ 30, so met", "C) population is Normal", "D) 10% condition only"],
          answer: "A) np = 8 < 10, so not met",
          hint: "Large counts needs both np and n(1−p) ≥ 10.",
          solution: "np = 8 fails; need larger n.",
        },
        {
          id: "st-sd-5", kind: "FRQ",
          prompt: "Soda bottles claim μ = 500 mL, σ = 6 mL. (a) For n = 36 bottles, describe the sampling distribution of the mean. (b) Find P(x̄ < 498). (c) Explain why the probability differs from P(one bottle < 498 mL).",
          answer: "(b) ≈ 0.023",
          hint: "SE = 6/√36 = 1; z = (498−500)/1.",
          solution: "(a) Approx Normal (n = 36), mean 500, SE 1. (b) z = −2 → ≈ 0.0228. (c) Averages vary far less than individuals, so extreme means are rarer than extreme single bottles.",
        },
        {
          id: "st-sd-6", kind: "FRQ",
          prompt: "Explain the Central Limit Theorem in plain language and why increasing n shrinks the standard error but does not change the population standard deviation.",
          answer: "Averages of large samples pile up Normally around μ with spread σ/√n",
          hint: "Averaging cancels individual extremes; σ describes individuals, σ/√n describes averages.",
          solution: "CLT: as n grows, x̄'s distribution centers on μ and approaches Normal with SE = σ/√n. Averaging smooths out extremes (smaller SE), while the population's own spread σ is a fixed property of individuals.",
        },
      ],
    },
    {
      id: "inference-prop",
      title: "Inference for Proportions",
      weight: "10–14%",
      concepts: [
        "One-sample z-interval and z-test for p",
        "Two-sample z-interval/test for p₁ − p₂",
        "Conditions: Random, 10%, Large Counts (z*) or expected counts ≥ 5/10",
        "Interpreting confidence levels and p-values; significance level α",
        "Type I/II errors and power in context",
      ],
      formulas: [
        "1-prop z-interval: p̂ ± z*√(p̂(1−p̂)/n)",
        "1-prop z-test: z = (p̂ − p₀)/√(p₀(1−p₀)/n)",
        "2-prop SE: √(p̂₁(1−p̂₁)/n₁ + p̂₂(1−p̂₂)/n₂)",
        "Pooled p̂ for tests: (x₁+x₂)/(n₁+n₂)",
      ],
      practice: [
        {
          id: "st-ip-1", kind: "MC",
          prompt: "A 95% CI for the proportion supporting a policy is (0.48, 0.56). Correct interpretation:",
          choices: ["A) 95% of voters lie in the interval", "B) we are 95% confident the true proportion is between 0.48 and 0.56", "C) P(true p in interval) = 0.95 for this specific interval", "D) 95% of samples give this exact interval"],
          answer: "B) we are 95% confident the true proportion is between 0.48 and 0.56",
          hint: "Confidence is about the method's long-run capture rate.",
          solution: "Standard confidence interpretation with context.",
        },
        {
          id: "st-ip-2", kind: "MC",
          prompt: "H₀: p = 0.5, p-value = 0.03, α = 0.05. Conclusion:",
          choices: ["A) fail to reject; no evidence", "B) reject H₀; convincing evidence p ≠ 0.5", "C) accept H₀", "D) power is 0.03"],
          answer: "B) reject H₀; convincing evidence p ≠ 0.5",
          hint: "p-value < α → reject.",
          solution: "0.03 < 0.05 → reject H₀.",
        },
        {
          id: "st-ip-3", kind: "MC",
          prompt: "Increasing confidence from 95% to 99% (same data) makes the interval:",
          choices: ["A) narrower", "B) wider", "C) unchanged", "D) centered elsewhere"],
          answer: "B) wider",
          hint: "Higher confidence needs a larger critical value.",
          solution: "z* grows (1.96 → 2.576), widening the margin.",
        },
        {
          id: "st-ip-4", kind: "MC",
          prompt: "A Type II error in a drug-effectiveness test means:",
          choices: ["A) concluding effective when it isn't", "B) failing to detect a real effect", "C) using the wrong α", "D) biased sampling"],
          answer: "B) failing to detect a real effect",
          hint: "Type II = false negative (fail to reject a false H₀).",
          solution: "The test misses a genuinely effective drug.",
        },
        {
          id: "st-ip-5", kind: "FRQ",
          prompt: "In 400 voters, 220 support Measure Q. (a) Give a 95% CI for the true proportion. (b) Test H₀: p = 0.5 vs. Hₐ: p > 0.5 at α = 0.05. (c) Do the answers agree? Explain.",
          answer: "(a) 0.55 ± 0.049; (b) z ≈ 2.0, p ≈ 0.023, reject",
          hint: "p̂ = 0.55; SE ≈ 0.0249 with z* = 1.96.",
          solution: "(a) 0.55 ± 1.96√(0.55·0.45/400) = 0.55 ± 0.049 → (0.501, 0.599). (b) z = (0.55−0.5)/0.025 = 2.0, p ≈ 0.023 < 0.05 → reject; evidence majority support. (c) Yes: interval lies above 0.5, consistent with rejection.",
        },
        {
          id: "st-ip-6", kind: "FRQ",
          prompt: "Two classes: 30/50 pass in A, 22/50 in B. Test whether pass rates differ (two-sided, α = 0.05). State hypotheses, check conditions, compute the test statistic, and conclude in context.",
          answer: "z ≈ 1.63, p ≈ 0.10, fail to reject",
          hint: "Use pooled p̂ = 52/100 = 0.52 for the SE.",
          solution: "H₀: p_A = p_B. Conditions: random classes assumed, independent, counts ≥ 10 ✓. z = (0.6−0.44)/√(0.52·0.48(1/50+1/50)) ≈ 1.63, p ≈ 0.103 → fail to reject; not convincing evidence of different pass rates.",
        },
      ],
    },
    {
      id: "inference-means",
      title: "Inference for Means & Slopes",
      weight: "12–15%",
      concepts: [
        "One-sample and paired t-intervals/tests; two-sample t (conservative df ok)",
        "t* critical values and degrees of freedom; when to use z vs. t",
        "Chi-square tests: goodness-of-fit, homogeneity, independence/association",
        "Inference for regression slope: conditions (LINER), t-test for β",
        "Choosing the right test: match data structure to procedure",
      ],
      formulas: [
        "t-interval: x̄ ± t*(s/√n), df = n−1",
        "t-test: t = (x̄ − μ₀)/(s/√n)",
        "χ² = Σ(O−E)²/E",
        "Slope SE output-based: t = b/SE_b",
        "Chi-square conditions: expected counts ≥ 5",
      ],
      practice: [
        {
          id: "st-im-1", kind: "MC",
          prompt: "n = 16 sleep hours, x̄ = 7.2, s = 1.0. A 95% CI uses critical value:",
          choices: ["A) z* = 1.96", "B) t* with 15 df ≈ 2.13", "C) t* with 16 df", "D) χ²"],
          answer: "B) t* with 15 df ≈ 2.13",
          hint: "σ unknown + small n → t with n−1 df.",
          solution: "df = 15, t* ≈ 2.131.",
        },
        {
          id: "st-im-2", kind: "MC",
          prompt: "Paired before/after data on 20 patients should be analyzed with:",
          choices: ["A) two-sample t-test", "B) one-sample t on differences", "C) chi-square", "D) two-proportion z"],
          answer: "B) one-sample t on differences",
          hint: "Pairing creates one sample of differences.",
          solution: "Analyze d = after − before with a one-sample t procedure.",
        },
        {
          id: "st-im-3", kind: "MC",
          prompt: "A χ² goodness-of-fit test with 4 categories rejected H₀. The conclusion is:",
          choices: ["A) all proportions differ from hypothesized", "B) the distribution differs somewhere from hypothesized", "C) two specific categories differ", "D) sample size was too small"],
          answer: "B) the distribution differs somewhere from hypothesized",
          hint: "χ² is an omnibus test — it doesn't say where.",
          solution: "Rejection means the overall distribution doesn't fit; follow-up comparisons needed for specifics.",
        },
        {
          id: "st-im-4", kind: "MC",
          prompt: "Regression slope b = 2.1, SE_b = 0.7, n = 25. The t-statistic for H₀: β = 0 is:",
          choices: ["A) 0.33", "B) 2.1", "C) 3.0", "D) 25"],
          answer: "C) 3.0",
          hint: "t = (b − 0)/SE_b.",
          solution: "2.1/0.7 = 3.0, df = 23.",
        },
        {
          id: "st-im-5", kind: "FRQ",
          prompt: "Battery lives (hrs): 12.1, 11.8, 12.5, 12.0, 11.6 (n = 5). Test H₀: μ = 12 vs. Hₐ: μ ≠ 12. Check conditions, compute t, and conclude at α = 0.05 (assume approximately Normal from a dotplot with no skew/outliers).",
          answer: "t ≈ 0, fail to reject",
          hint: "x̄ = 12.0, s ≈ 0.34.",
          solution: "x̄ = 12.0, s ≈ 0.342; t = (12−12)/(0.342/√5) = 0 → p = 1.0 → fail to reject; no evidence mean differs from 12 hrs. (Conditions: random sample stated, Normality reasonable for tiny n via plot.)",
        },
        {
          id: "st-im-6", kind: "FRQ",
          prompt: "A survey cross-tabulates grade (9–12) by preferred lunch (3 options), χ² = 18.2, df = 6, p = 0.006. (a) Name the procedure and hypotheses. (b) Conclude in context. (c) What would a segmented bar graph add?",
          answer: "Chi-square test of independence/association; reject — association exists",
          hint: "Two categorical variables from one sample → test of association.",
          solution: "(a) χ² test of association; H₀: grade and lunch preference independent. (b) p < 0.05 → reject; convincing evidence of association between grade and lunch choice. (c) Segmented bars show WHERE proportions differ across grades.",
        },
      ],
    },
  ],
};
